const fs = require('fs');
const path = require('path');

const initSqlPath = path.join(__dirname, '../migrations/init.sql');

async function run() {
    console.log('🚀 LocalSampark Index Generator Initializing...');
    const sql = fs.readFileSync(initSqlPath, 'utf8');

    // Prevent duplicate appends if script is run twice
    if (sql.includes('-- ─── DYNAMIC PERFORMANCE INDEXES ───')) {
        console.log('⚠️ Dynamic indexes have already been appended to init.sql.');
        return;
    }

    const lines = sql.split('\n');
    let currentTable = null;
    let standardIndexes = [];
    let geoIndexes = [];

    const tableRegex = /^CREATE TABLE IF NOT EXISTS\s+([a-zA-Z0-9_]+)\s*\(/i;
    const foreignKeyRegex = /^\s*([a-zA-Z0-9_]+)\s+.*REFERENCES\s+[a-zA-Z0-9_]+\s*\(/i;
    const geoRegex = /^\s*([a-zA-Z0-9_]+)\s+GEOGRAPHY\s*\(\s*Point/i;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];

        const tableMatch = line.match(tableRegex);
        if (tableMatch) {
            currentTable = tableMatch[1];
            continue;
        }

        if (currentTable) {
            // Check for end of table
            if (line.match(/^\s*\)\s*;/)) {
                currentTable = null;
                continue;
            }

            // Check for foreign keys
            const fkMatch = line.match(foreignKeyRegex);
            if (fkMatch) {
                const column = fkMatch[1];
                standardIndexes.push(`CREATE INDEX IF NOT EXISTS idx_${currentTable}_${column} ON ${currentTable}(${column});`);
                continue;
            }

            // Check for GEOGRAPHY
            const geoMatch = line.match(geoRegex);
            if (geoMatch) {
                const column = geoMatch[1];
                geoIndexes.push(`CREATE INDEX IF NOT EXISTS idx_geo_${currentTable}_${column} ON ${currentTable} USING GIST (${column});`);
                continue;
            }
        }
    }

    console.log(`✅ Found ${standardIndexes.length} Foreign Keys to index.`);
    console.log(`✅ Found ${geoIndexes.length} GEOGRAPHY columns to index.`);

    let appendSql = `\n\n-- ─── DYNAMIC PERFORMANCE INDEXES ────────────────────────────\n`;
    appendSql += `-- Auto-generated by Phase 12 Database Performance Audit\n\n`;

    appendSql += `-- Foreign Key B-Tree Indexes\n`;
    appendSql += standardIndexes.join('\n') + '\n\n';

    appendSql += `-- Geospatial GIST Indexes\n`;
    appendSql += geoIndexes.join('\n') + '\n\n';

    fs.appendFileSync(initSqlPath, appendSql);
    console.log('✅ Successfully appended performance indexes to init.sql.');
}

run().catch(console.error);
