# Start Live Tunnel (Ngrok) Script
Write-Host "=========================================================="
Write-Host "LocalSampark - Ngrok Live Tunneling Setup"
Write-Host "=========================================================="
Write-Host ""
Write-Host "This script guides you through setting up live public URLs for your local environment."
Write-Host "This is necessary for testing the Expo Mobile App on physical devices."
Write-Host ""
Write-Host "STEP 1: Start your backend and frontend servers"
Write-Host "----------------------------------------------------------"
Write-Host "Open a new terminal and run: cd backend && npm run dev (Runs on port 5000)"
Write-Host "Open a second terminal and run: cd apps/web && npm run dev (Runs on port 3000)"
Write-Host ""
Write-Host "STEP 2: Start Ngrok for the Backend API"
Write-Host "----------------------------------------------------------"
Write-Host "Open a third terminal and run:"
Write-Host "  ngrok http 5000"
Write-Host ""
Write-Host "Ngrok will output a 'Forwarding' URL (e.g., https://xyz.ngrok.app)."
Write-Host "Copy this URL."
Write-Host ""
Write-Host "STEP 3: Configure the Mobile App"
Write-Host "----------------------------------------------------------"
Write-Host "Go to apps/mobile/.env and update the API URL to point to the Ngrok URL:"
Write-Host "  EXPO_PUBLIC_API_URL=https://xyz.ngrok.app/api/v1"
Write-Host "  EXPO_PUBLIC_WS_URL=wss://xyz.ngrok.app"
Write-Host ""
Write-Host "STEP 4: Start the Expo Mobile Bundler"
Write-Host "----------------------------------------------------------"
Write-Host "Open a fourth terminal and run: cd apps/mobile && npx expo start -c"
Write-Host "Scan the QR code with your physical device."
Write-Host ""
Write-Host "(Optional) Start Ngrok for Web App"
Write-Host "----------------------------------------------------------"
Write-Host "If you want to test the Web App on your phone browser, run:"
Write-Host "  ngrok http 3000"
Write-Host "And visit that Ngrok URL."
Write-Host "=========================================================="
Write-Host "Happy bug hunting!"
