-- Migration 068: PostgreSQL parity for tables that existed only in SQLite
--
-- 44 tables were created by the .sqlite.sql migrations and by no
-- PostgreSQL migration. 36 of them are queried from the route layer, so those
-- endpoints return 500 in production while passing every local test — carpool,
-- jobs, marketplace chat/offers/auctions, and shop_settings (checkout path).
--
-- Generated by scripts/generate-pg-migrations.js. Column types are translated
-- from the SQLite DDL; foreign-key columns take their type from the referenced
-- table's primary key in the PostgreSQL schema, since SQLite declares
-- everything TEXT while PostgreSQL uses UUID for most primary keys.
--
-- NOT EXECUTED AGAINST POSTGRESQL. No PostgreSQL instance or Docker was
-- available when this was produced, so it is statically validated only.
-- Review before applying to production.

-- admin_jobs
CREATE TABLE IF NOT EXISTS admin_jobs (
 id TEXT PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text),
 title TEXT,
 description TEXT,
 salary TEXT,
 shop_name TEXT,
 status TEXT DEFAULT 'active',
 admin_id TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_bids
CREATE TABLE IF NOT EXISTS carpool_bids (
 id TEXT PRIMARY KEY,
 ride_id TEXT NOT NULL,
 bidder_id TEXT NOT NULL,
 bid_amount DOUBLE PRECISION NOT NULL,
 counter_amount DOUBLE PRECISION,
 seats_requested INTEGER DEFAULT 1,
 status TEXT DEFAULT 'pending',
 message TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_carbon_logs
CREATE TABLE IF NOT EXISTS carpool_carbon_logs (
 id SERIAL PRIMARY KEY,
 user_id TEXT NOT NULL,
 ride_id TEXT,
 distance_km DOUBLE PRECISION DEFAULT 0,
 co2_saved_kg DOUBLE PRECISION DEFAULT 0,
 fuel_saved_liters DOUBLE PRECISION DEFAULT 0,
 money_saved DOUBLE PRECISION DEFAULT 0,
 logged_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_chat_messages
CREATE TABLE IF NOT EXISTS carpool_chat_messages (
 id TEXT PRIMARY KEY,
 ride_id TEXT NOT NULL,
 sender_id TEXT NOT NULL,
 message TEXT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_corporate_verifications
CREATE TABLE IF NOT EXISTS carpool_corporate_verifications (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL UNIQUE,
 corporate_email TEXT,
 corporate_name TEXT,
 govt_id_type TEXT,
 govt_id_number TEXT,
 dl_number TEXT,
 is_verified INTEGER DEFAULT 0,
 verified_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_group_members
CREATE TABLE IF NOT EXISTS carpool_group_members (
 id SERIAL PRIMARY KEY,
 group_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 role TEXT DEFAULT 'member',
 joined_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(group_id, user_id)
);

-- carpool_groups
CREATE TABLE IF NOT EXISTS carpool_groups (
 id TEXT PRIMARY KEY,
 name TEXT NOT NULL,
 description TEXT,
 group_type TEXT DEFAULT 'commute',
 from_location TEXT,
 to_location TEXT,
 from_lat DOUBLE PRECISION,
 from_lng DOUBLE PRECISION,
 to_lat DOUBLE PRECISION,
 to_lng DOUBLE PRECISION,
 departure_time TEXT,
 days_active TEXT DEFAULT '["Mon","Tue","Wed","Thu","Fri"]',
 max_members INTEGER DEFAULT 20,
 created_by TEXT NOT NULL,
 is_active INTEGER DEFAULT 1,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_live_locations
CREATE TABLE IF NOT EXISTS carpool_live_locations (
 id SERIAL PRIMARY KEY,
 ride_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 latitude DOUBLE PRECISION NOT NULL,
 longitude DOUBLE PRECISION NOT NULL,
 speed DOUBLE PRECISION DEFAULT 0,
 heading DOUBLE PRECISION DEFAULT 0,
 accuracy DOUBLE PRECISION DEFAULT 0,
 recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_ratings
CREATE TABLE IF NOT EXISTS carpool_ratings (
 id TEXT PRIMARY KEY,
 ride_id TEXT NOT NULL,
 rater_id TEXT NOT NULL,
 rated_id TEXT NOT NULL,
 rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
 comment TEXT,
 role TEXT DEFAULT 'passenger',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(ride_id, rater_id)
);

-- carpool_recurring_rides
CREATE TABLE IF NOT EXISTS carpool_recurring_rides (
 id TEXT PRIMARY KEY,
 driver_id TEXT NOT NULL,
 vehicle_id TEXT,
 from_location TEXT NOT NULL,
 to_location TEXT NOT NULL,
 from_lat DOUBLE PRECISION,
 from_lng DOUBLE PRECISION,
 to_lat DOUBLE PRECISION,
 to_lng DOUBLE PRECISION,
 departure_time TEXT NOT NULL,
 days_of_week TEXT DEFAULT '1,2,3,4,5',
 seats_available INTEGER DEFAULT 3,
 price_per_seat DOUBLE PRECISION DEFAULT 0,
 ride_type TEXT DEFAULT 'car',
 gender_preference TEXT DEFAULT 'any',
 is_active INTEGER DEFAULT 1,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_ride_otps
CREATE TABLE IF NOT EXISTS carpool_ride_otps (
 id SERIAL PRIMARY KEY,
 ride_id TEXT NOT NULL,
 booking_id INTEGER NOT NULL,
 otp_code TEXT NOT NULL,
 verified INTEGER DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(ride_id, booking_id)
);

-- carpool_ride_waypoints
CREATE TABLE IF NOT EXISTS carpool_ride_waypoints (
 id TEXT PRIMARY KEY,
 ride_id TEXT NOT NULL,
 location_name TEXT NOT NULL,
 latitude DOUBLE PRECISION,
 longitude DOUBLE PRECISION,
 stop_order INTEGER DEFAULT 0,
 estimated_time TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_sos_alerts
CREATE TABLE IF NOT EXISTS carpool_sos_alerts (
 id TEXT PRIMARY KEY,
 ride_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 latitude DOUBLE PRECISION,
 longitude DOUBLE PRECISION,
 alert_type TEXT DEFAULT 'emergency',
 message TEXT,
 status TEXT DEFAULT 'active',
 resolved_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- carpool_vehicles
CREATE TABLE IF NOT EXISTS carpool_vehicles (
 id TEXT PRIMARY KEY,
 owner_id TEXT NOT NULL,
 vehicle_type TEXT DEFAULT 'car',
 make TEXT,
 model TEXT,
 color TEXT,
 plate_number TEXT,
 photo_url TEXT,
 total_seats INTEGER DEFAULT 4,
 fuel_type TEXT DEFAULT 'petrol',
 is_verified INTEGER DEFAULT 0,
 verification_doc_url TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- company_profiles
CREATE TABLE IF NOT EXISTS company_profiles (
 id TEXT PRIMARY KEY,
 owner_id TEXT,
 name TEXT NOT NULL,
 logo_url TEXT,
 website TEXT,
 industry TEXT,
 description TEXT,
 employee_count TEXT,
 founded_year INTEGER,
 headquarters TEXT,
 average_rating DOUBLE PRECISION DEFAULT 0,
 review_count INTEGER DEFAULT 0,
 is_verified INTEGER DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- company_reviews
CREATE TABLE IF NOT EXISTS company_reviews (
 id TEXT PRIMARY KEY,
 company_id TEXT NOT NULL,
 reviewer_id TEXT NOT NULL,
 overall_rating INTEGER NOT NULL CHECK(overall_rating >= 1 AND overall_rating <= 5),
 work_life_rating INTEGER CHECK(work_life_rating >= 1 AND work_life_rating <= 5),
 salary_rating INTEGER CHECK(salary_rating >= 1 AND salary_rating <= 5),
 culture_rating INTEGER CHECK(culture_rating >= 1 AND culture_rating <= 5),
 management_rating INTEGER CHECK(management_rating >= 1 AND management_rating <= 5),
 title TEXT,
 pros TEXT,
 cons TEXT,
 advice TEXT,
 is_current_employee INTEGER DEFAULT 0,
 employment_status TEXT,
 job_title TEXT,
 is_anonymous INTEGER DEFAULT 1,
 status TEXT DEFAULT 'active',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- employer_job_analytics
CREATE TABLE IF NOT EXISTS employer_job_analytics (
 id SERIAL PRIMARY KEY,
 job_id TEXT NOT NULL,
 employer_id TEXT NOT NULL,
 views INTEGER DEFAULT 0,
 applications INTEGER DEFAULT 0,
 shortlisted INTEGER DEFAULT 0,
 hired INTEGER DEFAULT 0,
 avg_match_score DOUBLE PRECISION DEFAULT 0,
 top_skills_applied TEXT,
 date TEXT NOT NULL,
  UNIQUE(job_id, date)
);

-- job_alerts
CREATE TABLE IF NOT EXISTS job_alerts (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 keywords TEXT,
 job_type TEXT,
 sector TEXT,
 min_salary DOUBLE PRECISION,
 location TEXT,
 is_active INTEGER DEFAULT 1,
 last_sent_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- job_assessment_attempts
CREATE TABLE IF NOT EXISTS job_assessment_attempts (
 id SERIAL PRIMARY KEY,
 assessment_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 score INTEGER DEFAULT 0,
 passed INTEGER DEFAULT 0,
 answers TEXT,
 started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMP WITH TIME ZONE
);

-- job_chat_messages
CREATE TABLE IF NOT EXISTS job_chat_messages (
 id TEXT PRIMARY KEY,
 chat_id TEXT NOT NULL,
 sender_id TEXT NOT NULL,
 message TEXT NOT NULL,
 message_type TEXT DEFAULT 'text',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- job_direct_chats
CREATE TABLE IF NOT EXISTS job_direct_chats (
 id TEXT PRIMARY KEY,
 job_id TEXT,
 candidate_id TEXT NOT NULL,
 recruiter_id TEXT NOT NULL,
 last_message TEXT,
 last_message_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(job_id, candidate_id, recruiter_id)
);

-- job_interviews
CREATE TABLE IF NOT EXISTS job_interviews (
 id TEXT PRIMARY KEY,
 application_id TEXT NOT NULL,
 job_id TEXT NOT NULL,
 candidate_id TEXT NOT NULL,
 recruiter_id TEXT,
 interview_type TEXT DEFAULT 'in_person',
 scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
 duration_minutes INTEGER DEFAULT 30,
 location TEXT,
 meeting_link TEXT,
 notes TEXT,
 status TEXT DEFAULT 'scheduled',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- job_referrals
CREATE TABLE IF NOT EXISTS job_referrals (
 id TEXT PRIMARY KEY,
 job_id TEXT NOT NULL,
 referrer_id TEXT NOT NULL,
 referred_user_id TEXT,
 referral_code TEXT NOT NULL UNIQUE,
 status TEXT DEFAULT 'pending',
 bounty_amount DOUBLE PRECISION DEFAULT 0,
 bounty_paid INTEGER DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 converted_at TIMESTAMP WITH TIME ZONE
);

-- job_required_skills
CREATE TABLE IF NOT EXISTS job_required_skills (
 id TEXT PRIMARY KEY,
 job_id TEXT NOT NULL,
 skill_name TEXT NOT NULL,
 importance TEXT DEFAULT 'required',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(job_id, skill_name)
);

-- job_resumes
CREATE TABLE IF NOT EXISTS job_resumes (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 file_url TEXT,
 file_name TEXT,
 parsed_text TEXT,
 parsed_skills TEXT DEFAULT '[]',
 experience_years DOUBLE PRECISION DEFAULT 0,
 education TEXT,
 headline TEXT,
 summary TEXT,
 voice_intro_url TEXT,
 health_score INTEGER DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE job_resumes ADD COLUMN IF NOT EXISTS video_resume_url TEXT;
ALTER TABLE job_resumes ADD COLUMN IF NOT EXISTS pdf_resume_url TEXT;
ALTER TABLE job_resumes ADD COLUMN IF NOT EXISTS parsed_data TEXT;

-- job_salary_insights
CREATE TABLE IF NOT EXISTS job_salary_insights (
 id TEXT PRIMARY KEY,
 job_title TEXT NOT NULL,
 company_id TEXT,
 company_name TEXT,
 salary_min DOUBLE PRECISION,
 salary_max DOUBLE PRECISION,
 salary_avg DOUBLE PRECISION,
 currency TEXT DEFAULT 'INR',
 pay_period TEXT DEFAULT 'monthly',
 experience_years DOUBLE PRECISION,
 location TEXT,
 is_anonymous INTEGER DEFAULT 1,
 submitted_by TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- job_saved
CREATE TABLE IF NOT EXISTS job_saved (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 job_id TEXT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, job_id)
);

-- job_skill_assessments
CREATE TABLE IF NOT EXISTS job_skill_assessments (
 id TEXT PRIMARY KEY,
 skill_name TEXT NOT NULL,
 questions TEXT NOT NULL,
 passing_score INTEGER DEFAULT 70,
 time_limit_seconds INTEGER DEFAULT 300,
 difficulty TEXT DEFAULT 'intermediate',
 is_active INTEGER DEFAULT 1,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- job_skills
CREATE TABLE IF NOT EXISTS job_skills (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 skill_name TEXT NOT NULL,
 proficiency TEXT DEFAULT 'intermediate',
 years_experience DOUBLE PRECISION DEFAULT 0,
 is_verified INTEGER DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, skill_name)
);

-- job_walkin_events
CREATE TABLE IF NOT EXISTS job_walkin_events (
 id TEXT PRIMARY KEY,
 employer_id TEXT NOT NULL,
 title TEXT NOT NULL,
 company_name TEXT,
 location TEXT,
 latitude DOUBLE PRECISION,
 longitude DOUBLE PRECISION,
 event_date TEXT NOT NULL,
 start_time TEXT,
 end_time TEXT,
 positions_available TEXT,
 requirements TEXT,
 max_candidates INTEGER DEFAULT 50,
 registered_count INTEGER DEFAULT 0,
 is_active INTEGER DEFAULT 1,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_auction_bids
CREATE TABLE IF NOT EXISTS marketplace_auction_bids (
 id SERIAL PRIMARY KEY,
 auction_id TEXT NOT NULL,
 bidder_id TEXT NOT NULL,
 bid_amount DOUBLE PRECISION NOT NULL,
 bid_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_auctions
CREATE TABLE IF NOT EXISTS marketplace_auctions (
 id TEXT PRIMARY KEY,
 listing_id TEXT NOT NULL UNIQUE,
 starting_price DOUBLE PRECISION NOT NULL,
 current_bid DOUBLE PRECISION DEFAULT 0,
 bid_increment DOUBLE PRECISION DEFAULT 50,
 highest_bidder_id TEXT,
 total_bids INTEGER DEFAULT 0,
 starts_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
 status TEXT DEFAULT 'active',
 winner_id TEXT
);

-- marketplace_categories
CREATE TABLE IF NOT EXISTS marketplace_categories (
 id TEXT PRIMARY KEY,
 name TEXT NOT NULL UNIQUE,
 icon TEXT,
 display_order INTEGER DEFAULT 0,
 is_active INTEGER DEFAULT 1,
 parent_id TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_chat_messages
CREATE TABLE IF NOT EXISTS marketplace_chat_messages (
 id TEXT PRIMARY KEY,
 chat_id TEXT NOT NULL,
 sender_id TEXT NOT NULL,
 message TEXT NOT NULL,
 message_type TEXT DEFAULT 'text',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_chats
CREATE TABLE IF NOT EXISTS marketplace_chats (
 id TEXT PRIMARY KEY,
 listing_id TEXT NOT NULL,
 buyer_id TEXT NOT NULL,
 seller_id TEXT NOT NULL,
 last_message TEXT,
 last_message_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(listing_id, buyer_id)
);

-- marketplace_escrow
CREATE TABLE IF NOT EXISTS marketplace_escrow (
 id TEXT PRIMARY KEY,
 listing_id TEXT NOT NULL,
 buyer_id TEXT NOT NULL,
 seller_id TEXT NOT NULL,
 amount DOUBLE PRECISION NOT NULL,
 platform_fee DOUBLE PRECISION DEFAULT 0,
 status TEXT DEFAULT 'held',
 payment_method TEXT DEFAULT 'wallet',
 razorpay_payment_id TEXT,
 razorpay_order_id TEXT,
 held_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 released_at TIMESTAMP WITH TIME ZONE,
 refunded_at TIMESTAMP WITH TIME ZONE,
 dispute_reason TEXT,
 dispute_at TIMESTAMP WITH TIME ZONE,
 resolved_at TIMESTAMP WITH TIME ZONE
);

-- marketplace_offers
CREATE TABLE IF NOT EXISTS marketplace_offers (
 id TEXT PRIMARY KEY,
 listing_id TEXT NOT NULL,
 buyer_id TEXT NOT NULL,
 offer_amount DOUBLE PRECISION NOT NULL,
 counter_amount DOUBLE PRECISION,
 message TEXT,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_price_alerts
CREATE TABLE IF NOT EXISTS marketplace_price_alerts (
 id SERIAL PRIMARY KEY,
 user_id TEXT NOT NULL,
 listing_id TEXT,
 category TEXT,
 max_price DOUBLE PRECISION,
 keywords TEXT,
 is_active INTEGER DEFAULT 1,
 last_notified TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_reports
CREATE TABLE IF NOT EXISTS marketplace_reports (
 id TEXT PRIMARY KEY,
 listing_id TEXT NOT NULL,
 reporter_id TEXT NOT NULL,
 reason TEXT NOT NULL,
 details TEXT,
 status TEXT DEFAULT 'pending',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- marketplace_saved
CREATE TABLE IF NOT EXISTS marketplace_saved (
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL,
 listing_id TEXT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, listing_id)
);

-- marketplace_seller_scores
CREATE TABLE IF NOT EXISTS marketplace_seller_scores (
 id SERIAL PRIMARY KEY,
 seller_id TEXT NOT NULL UNIQUE,
 account_age_days INTEGER DEFAULT 0,
 verified_phone INTEGER DEFAULT 0,
 verified_email INTEGER DEFAULT 0,
 verified_id INTEGER DEFAULT 0,
 total_listings INTEGER DEFAULT 0,
 total_sold INTEGER DEFAULT 0,
 avg_rating DOUBLE PRECISION DEFAULT 0,
 avg_response_time_mins DOUBLE PRECISION DEFAULT 0,
 dispute_count INTEGER DEFAULT 0,
 trust_score DOUBLE PRECISION DEFAULT 50,
 last_calculated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- shop_settings
CREATE TABLE IF NOT EXISTS shop_settings (
 id TEXT PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text),
 shop_id TEXT NOT NULL,
 settings TEXT DEFAULT '{}',
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(shop_id)
);

-- skilled_bookings
CREATE TABLE IF NOT EXISTS skilled_bookings (
 id TEXT PRIMARY KEY,
 customer_id UUID REFERENCES users(id) ON DELETE CASCADE,
 assigned_worker_id UUID REFERENCES users(id) ON DELETE SET NULL,
 service_category TEXT NOT NULL,
 description TEXT,
 address TEXT NOT NULL,
 preferred_date TEXT,
 status TEXT DEFAULT 'pending', -- pending, assigned, completed, cancelled,
 created_at TEXT DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- universal_orders_new
CREATE TABLE IF NOT EXISTS universal_orders_new (
 id SERIAL PRIMARY KEY,
 shop_id TEXT,
 user_id TEXT,
 status TEXT DEFAULT 'pending',
 total_amount DOUBLE PRECISION DEFAULT 0,
 order_type TEXT DEFAULT 'ecom',
 scheduled_time TIMESTAMP WITH TIME ZONE,
 delivery_address TEXT,
 notes TEXT,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 rider_id TEXT
);
