-- Migration 076 (SQLite): restore columns lost to duplicate CREATE TABLE declarations
--
-- Several tables are declared twice with CREATE TABLE IF NOT EXISTS: once as an
-- early stub and once, later, in full. Migrations run in filename order, so on a
-- fresh database the stub wins and the full declaration silently does nothing.
-- society_assets is the clearest case -- a new deployment gets 7 columns with a
-- `name`, while the application queries `asset_name` against 23.
--
-- The development database was built before the migrations reached their current
-- order, so it has the full tables. That is precisely why this went unnoticed:
-- the only database anyone inspects is the one that happens to be correct, while
-- every genuinely new environment -- CI, staging, production -- would get stubs.
--
-- These statements were generated by diffing a freshly-migrated database against
-- the live one (scripts/generate-fresh-parity-migration.js), not written by hand,
-- so the column list is measured rather than remembered.
--
-- On the development database every statement here is a no-op.
-- SQLite has no ADD COLUMN IF NOT EXISTS; the runner tolerates "duplicate
-- column name" so re-running stays safe.

-- community_posts: 4 column(s) absent from a fresh migration
ALTER TABLE community_posts ADD COLUMN type TEXT DEFAULT 'discussion';
ALTER TABLE community_posts ADD COLUMN likes INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN comments INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN is_pinned INTEGER DEFAULT 0;

-- delivery_jobs: 1 column(s) absent from a fresh migration
ALTER TABLE delivery_jobs ADD COLUMN agent_id INTEGER;

-- feature_flags: 2 column(s) absent from a fresh migration
ALTER TABLE feature_flags ADD COLUMN name TEXT;
ALTER TABLE feature_flags ADD COLUMN created_at DATETIME;

-- franchise_partners: 9 column(s) absent from a fresh migration
ALTER TABLE franchise_partners ADD COLUMN product_commission_percent REAL DEFAULT 5.0;
ALTER TABLE franchise_partners ADD COLUMN skilled_job_commission_percent REAL DEFAULT 10.0;
ALTER TABLE franchise_partners ADD COLUMN event_ticket_commission_percent REAL DEFAULT 5.0;
ALTER TABLE franchise_partners ADD COLUMN delivery_base_fee REAL DEFAULT 20.0;
ALTER TABLE franchise_partners ADD COLUMN property_listing_fee REAL DEFAULT 500.0;
ALTER TABLE franchise_partners ADD COLUMN marketplace_listing_fee REAL DEFAULT 50.0;
ALTER TABLE franchise_partners ADD COLUMN platform_profit_split REAL DEFAULT 60.0;
ALTER TABLE franchise_partners ADD COLUMN reward_pool_split REAL DEFAULT 20.0;
ALTER TABLE franchise_partners ADD COLUMN reserve_split REAL DEFAULT 20.0;

-- home_service_bookings: 3 column(s) absent from a fresh migration
ALTER TABLE home_service_bookings ADD COLUMN customer_id INTEGER;
ALTER TABLE home_service_bookings ADD COLUMN service_type TEXT;
ALTER TABLE home_service_bookings ADD COLUMN is_payout_settled INTEGER DEFAULT 0;

-- home_service_providers: 2 column(s) absent from a fresh migration
ALTER TABLE home_service_providers ADD COLUMN service_type TEXT;
ALTER TABLE home_service_providers ADD COLUMN wallet_balance REAL DEFAULT 0;

-- job_walkin_events: 4 column(s) absent from a fresh migration
ALTER TABLE job_walkin_events ADD COLUMN lat REAL;
ALTER TABLE job_walkin_events ADD COLUMN lng REAL;
ALTER TABLE job_walkin_events ADD COLUMN positions TEXT;
ALTER TABLE job_walkin_events ADD COLUMN salary_range TEXT;

-- local_job_postings: 4 column(s) absent from a fresh migration
ALTER TABLE local_job_postings ADD COLUMN shop_id TEXT;
ALTER TABLE local_job_postings ADD COLUMN description TEXT;
ALTER TABLE local_job_postings ADD COLUMN salary REAL;
ALTER TABLE local_job_postings ADD COLUMN updated_at DATETIME;

-- local_shops: 4 column(s) absent from a fresh migration
ALTER TABLE local_shops ADD COLUMN pincode TEXT;
ALTER TABLE local_shops ADD COLUMN phone TEXT;
ALTER TABLE local_shops ADD COLUMN rating REAL DEFAULT 0;
ALTER TABLE local_shops ADD COLUMN is_featured INTEGER DEFAULT 0;

-- localization_dictionaries: 1 column(s) absent from a fresh migration
ALTER TABLE localization_dictionaries ADD COLUMN created_at DATETIME;

-- loyalty_transactions: 2 column(s) absent from a fresh migration
ALTER TABLE loyalty_transactions ADD COLUMN type TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN source TEXT;

-- marketplace_auctions: 1 column(s) absent from a fresh migration
ALTER TABLE marketplace_auctions ADD COLUMN created_at DATETIME;

-- marketplace_escrow: 1 column(s) absent from a fresh migration
ALTER TABLE marketplace_escrow ADD COLUMN created_at DATETIME;

-- medical_providers: 3 column(s) absent from a fresh migration
ALTER TABLE medical_providers ADD COLUMN name TEXT;
ALTER TABLE medical_providers ADD COLUMN address TEXT;
ALTER TABLE medical_providers ADD COLUMN contact_number TEXT;

-- move_passes: 13 column(s) absent from a fresh migration
ALTER TABLE move_passes ADD COLUMN requested_by TEXT;
ALTER TABLE move_passes ADD COLUMN flat_owner_id TEXT;
ALTER TABLE move_passes ADD COLUMN move_type TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN move_date TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN clearance_status TEXT DEFAULT 'pending';
ALTER TABLE move_passes ADD COLUMN outstanding_dues REAL DEFAULT 0;
ALTER TABLE move_passes ADD COLUMN gate_passcode TEXT;
ALTER TABLE move_passes ADD COLUMN movers_company TEXT;
ALTER TABLE move_passes ADD COLUMN movers_vehicle_number TEXT;
ALTER TABLE move_passes ADD COLUMN admin_approved_at TEXT;
ALTER TABLE move_passes ADD COLUMN admin_approved_by TEXT;
ALTER TABLE move_passes ADD COLUMN notes TEXT;
ALTER TABLE move_passes ADD COLUMN created_at TEXT;

-- shop_categories: 14 column(s) absent from a fresh migration
ALTER TABLE shop_categories ADD COLUMN name_mr TEXT;
ALTER TABLE shop_categories ADD COLUMN name_hi TEXT;
ALTER TABLE shop_categories ADD COLUMN archetype TEXT DEFAULT 'retail';
ALTER TABLE shop_categories ADD COLUMN parent_category_id TEXT;
ALTER TABLE shop_categories ADD COLUMN requires_fssai INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN requires_gst INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN requires_drug_license INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN supports_delivery INTEGER DEFAULT 1;
ALTER TABLE shop_categories ADD COLUMN supports_pickup INTEGER DEFAULT 1;
ALTER TABLE shop_categories ADD COLUMN supports_appointment INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN supports_subscription INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN supports_table_booking INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN default_commission_pct REAL DEFAULT 10.0;
ALTER TABLE shop_categories ADD COLUMN min_order_amount REAL DEFAULT 0;

-- shop_orders: 2 column(s) absent from a fresh migration
ALTER TABLE shop_orders ADD COLUMN customer_id INTEGER;
ALTER TABLE shop_orders ADD COLUMN payment_gateway_ref TEXT;

-- shop_products: 3 column(s) absent from a fresh migration
ALTER TABLE shop_products ADD COLUMN mrp REAL;
ALTER TABLE shop_products ADD COLUMN stock INTEGER DEFAULT 0;
ALTER TABLE shop_products ADD COLUMN is_active INTEGER DEFAULT 1;

-- society_admin_roles: 4 column(s) absent from a fresh migration
ALTER TABLE society_admin_roles ADD COLUMN appointed_at TEXT;
ALTER TABLE society_admin_roles ADD COLUMN appointed_by TEXT;
ALTER TABLE society_admin_roles ADD COLUMN expires_at TEXT;
ALTER TABLE society_admin_roles ADD COLUMN created_at TEXT;

-- society_advance_account: 6 column(s) absent from a fresh migration
ALTER TABLE society_advance_account ADD COLUMN member_id TEXT DEFAULT '';
ALTER TABLE society_advance_account ADD COLUMN credit_amount REAL DEFAULT 0;
ALTER TABLE society_advance_account ADD COLUMN utilized_amount REAL DEFAULT 0;
ALTER TABLE society_advance_account ADD COLUMN source TEXT;
ALTER TABLE society_advance_account ADD COLUMN reference_bill_id TEXT;
ALTER TABLE society_advance_account ADD COLUMN created_at TEXT;

-- society_agm_meetings: 7 column(s) absent from a fresh migration
ALTER TABLE society_agm_meetings ADD COLUMN meeting_type TEXT DEFAULT '';
ALTER TABLE society_agm_meetings ADD COLUMN description TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN start_time TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN end_time TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN attendees_count INTEGER DEFAULT 0;
ALTER TABLE society_agm_meetings ADD COLUMN created_by TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN created_at TEXT;

-- society_agm_minutes: 6 column(s) absent from a fresh migration
ALTER TABLE society_agm_minutes ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_agm_minutes ADD COLUMN resolutions TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN attendees TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN recorded_by TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN published_at TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN document_url TEXT;

-- society_amenity_locks: 5 column(s) absent from a fresh migration
ALTER TABLE society_amenity_locks ADD COLUMN booking_date TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN start_time TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN end_time TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN locked_by TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN created_at TEXT;

-- society_asset_maintenance_log: 10 column(s) absent from a fresh migration
ALTER TABLE society_asset_maintenance_log ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_asset_maintenance_log ADD COLUMN maintenance_type TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN description TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN performed_by TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN vendor_id TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN parts_replaced TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN performed_at TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN next_due TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN photo_urls TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN created_at TEXT;

-- society_assets: 19 column(s) absent from a fresh migration
ALTER TABLE society_assets ADD COLUMN asset_name TEXT DEFAULT '';
ALTER TABLE society_assets ADD COLUMN asset_type TEXT;
ALTER TABLE society_assets ADD COLUMN asset_code TEXT;
ALTER TABLE society_assets ADD COLUMN location TEXT;
ALTER TABLE society_assets ADD COLUMN make_model TEXT;
ALTER TABLE society_assets ADD COLUMN serial_number TEXT;
ALTER TABLE society_assets ADD COLUMN purchase_date TEXT;
ALTER TABLE society_assets ADD COLUMN purchase_cost REAL DEFAULT 0;
ALTER TABLE society_assets ADD COLUMN installation_date TEXT;
ALTER TABLE society_assets ADD COLUMN warranty_expiry TEXT;
ALTER TABLE society_assets ADD COLUMN amc_start_date TEXT;
ALTER TABLE society_assets ADD COLUMN amc_end_date TEXT;
ALTER TABLE society_assets ADD COLUMN amc_cost REAL DEFAULT 0;
ALTER TABLE society_assets ADD COLUMN last_serviced_at TEXT;
ALTER TABLE society_assets ADD COLUMN next_service_due TEXT;
ALTER TABLE society_assets ADD COLUMN photo_url TEXT;
ALTER TABLE society_assets ADD COLUMN notes TEXT;
ALTER TABLE society_assets ADD COLUMN created_at TEXT;
ALTER TABLE society_assets ADD COLUMN updated_at TEXT;

-- society_billing_config: 11 column(s) absent from a fresh migration
ALTER TABLE society_billing_config ADD COLUMN sinking_fund_rate REAL DEFAULT 0.25;
ALTER TABLE society_billing_config ADD COLUMN max_late_interest_rate REAL DEFAULT 21.0;
ALTER TABLE society_billing_config ADD COLUMN actual_late_interest_rate REAL DEFAULT 18.0;
ALTER TABLE society_billing_config ADD COLUMN noc_percentage REAL DEFAULT 10.0;
ALTER TABLE society_billing_config ADD COLUMN grace_period_days INTEGER DEFAULT 15;
ALTER TABLE society_billing_config ADD COLUMN gst_rate REAL DEFAULT 18.0;
ALTER TABLE society_billing_config ADD COLUMN tds_enabled INTEGER DEFAULT 0;
ALTER TABLE society_billing_config ADD COLUMN tds_rate REAL DEFAULT 2.0;
ALTER TABLE society_billing_config ADD COLUMN parking_charge_two_wheeler REAL DEFAULT 200.0;
ALTER TABLE society_billing_config ADD COLUMN parking_charge_four_wheeler REAL DEFAULT 500.0;
ALTER TABLE society_billing_config ADD COLUMN created_at TEXT;

-- society_budget: 7 column(s) absent from a fresh migration
ALTER TABLE society_budget ADD COLUMN financial_year TEXT DEFAULT '';
ALTER TABLE society_budget ADD COLUMN total_budget REAL DEFAULT 0;
ALTER TABLE society_budget ADD COLUMN total_income_projected REAL DEFAULT 0;
ALTER TABLE society_budget ADD COLUMN status TEXT DEFAULT 'draft';
ALTER TABLE society_budget ADD COLUMN approved_by TEXT;
ALTER TABLE society_budget ADD COLUMN approved_at TEXT;
ALTER TABLE society_budget ADD COLUMN notes TEXT;

-- society_budget_items: 5 column(s) absent from a fresh migration
ALTER TABLE society_budget_items ADD COLUMN description TEXT;
ALTER TABLE society_budget_items ADD COLUMN budgeted_amount REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN actual_amount REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN variance REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN created_at TEXT;

-- society_cab_preapprovals: 3 column(s) absent from a fresh migration
ALTER TABLE society_cab_preapprovals ADD COLUMN resident_id TEXT DEFAULT '';
ALTER TABLE society_cab_preapprovals ADD COLUMN vehicle_number TEXT;
ALTER TABLE society_cab_preapprovals ADD COLUMN used_at TEXT;

-- society_charge_heads: 5 column(s) absent from a fresh migration
ALTER TABLE society_charge_heads ADD COLUMN formula TEXT;
ALTER TABLE society_charge_heads ADD COLUMN is_gst_applicable INTEGER DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN gst_rate REAL DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN sort_order INTEGER DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN created_at TEXT;

-- society_complaint_activity: 6 column(s) absent from a fresh migration
ALTER TABLE society_complaint_activity ADD COLUMN society_id TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN action TEXT DEFAULT '';
ALTER TABLE society_complaint_activity ADD COLUMN from_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN to_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN performed_by TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN performer_name TEXT;

-- society_delivery_preferences: 8 column(s) absent from a fresh migration
ALTER TABLE society_delivery_preferences ADD COLUMN member_id TEXT DEFAULT '';
ALTER TABLE society_delivery_preferences ADD COLUMN preferred_window_start TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN preferred_window_end TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN default_leave_at_gate INTEGER DEFAULT 0;
ALTER TABLE society_delivery_preferences ADD COLUMN preferred_package_location TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN special_instructions TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN created_at TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN updated_at TEXT;

-- society_document_templates: 6 column(s) absent from a fresh migration
ALTER TABLE society_document_templates ADD COLUMN template_name TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN template_type TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN template_content TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN variables TEXT;
ALTER TABLE society_document_templates ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE society_document_templates ADD COLUMN created_at TEXT;

-- society_emergency_alerts: 1 column(s) absent from a fresh migration
ALTER TABLE society_emergency_alerts ADD COLUMN updated_at DATETIME;

-- society_expense_categories: 4 column(s) absent from a fresh migration
ALTER TABLE society_expense_categories ADD COLUMN parent_category TEXT;
ALTER TABLE society_expense_categories ADD COLUMN budget_amount REAL DEFAULT 0;
ALTER TABLE society_expense_categories ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE society_expense_categories ADD COLUMN created_at TEXT;

-- society_fire_safety: 11 column(s) absent from a fresh migration
ALTER TABLE society_fire_safety ADD COLUMN equipment_name TEXT DEFAULT '';
ALTER TABLE society_fire_safety ADD COLUMN serial_number TEXT;
ALTER TABLE society_fire_safety ADD COLUMN last_inspection_date TEXT;
ALTER TABLE society_fire_safety ADD COLUMN next_inspection_due TEXT;
ALTER TABLE society_fire_safety ADD COLUMN inspection_vendor TEXT;
ALTER TABLE society_fire_safety ADD COLUMN noc_number TEXT;
ALTER TABLE society_fire_safety ADD COLUMN noc_expiry TEXT;
ALTER TABLE society_fire_safety ADD COLUMN photo_url TEXT;
ALTER TABLE society_fire_safety ADD COLUMN notes TEXT;
ALTER TABLE society_fire_safety ADD COLUMN created_at TEXT;
ALTER TABLE society_fire_safety ADD COLUMN updated_at TEXT;

-- society_flat_ledger: 12 column(s) absent from a fresh migration
ALTER TABLE society_flat_ledger ADD COLUMN member_id TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN carpet_area_sqft REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN construction_cost REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN advance_balance REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN total_arrears REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN tenant_name TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN tenant_phone TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN tenant_lease_start TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN police_verification_status TEXT DEFAULT 'not_required';
ALTER TABLE society_flat_ledger ADD COLUMN police_verification_doc_url TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN police_verification_expiry TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN created_at TEXT;

-- society_forum_replies: 4 column(s) absent from a fresh migration
ALTER TABLE society_forum_replies ADD COLUMN likes_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_replies ADD COLUMN liked_by TEXT DEFAULT '[]';
ALTER TABLE society_forum_replies ADD COLUMN is_edited INTEGER DEFAULT 0;
ALTER TABLE society_forum_replies ADD COLUMN updated_at TEXT;

-- society_forum_topics: 6 column(s) absent from a fresh migration
ALTER TABLE society_forum_topics ADD COLUMN created_by TEXT DEFAULT '';
ALTER TABLE society_forum_topics ADD COLUMN reply_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_topics ADD COLUMN view_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_topics ADD COLUMN last_reply_at TEXT;
ALTER TABLE society_forum_topics ADD COLUMN last_reply_by TEXT;
ALTER TABLE society_forum_topics ADD COLUMN updated_at TEXT;

-- society_gates: 5 column(s) absent from a fresh migration
ALTER TABLE society_gates ADD COLUMN gate_name TEXT DEFAULT '';
ALTER TABLE society_gates ADD COLUMN gate_type TEXT DEFAULT 'main';
ALTER TABLE society_gates ADD COLUMN location_description TEXT;
ALTER TABLE society_gates ADD COLUMN assigned_guards TEXT;
ALTER TABLE society_gates ADD COLUMN created_at TEXT;

-- society_guard_reminders: 1 column(s) absent from a fresh migration
ALTER TABLE society_guard_reminders ADD COLUMN updated_at DATETIME;

-- society_guard_shift_swaps: 9 column(s) absent from a fresh migration
ALTER TABLE society_guard_shift_swaps ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN requester_guard_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN target_guard_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN requester_shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN target_shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN approved_by TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN approved_at TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN reason TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN created_at TEXT;

-- society_guard_shifts: 7 column(s) absent from a fresh migration
ALTER TABLE society_guard_shifts ADD COLUMN shift_type TEXT DEFAULT '';
ALTER TABLE society_guard_shifts ADD COLUMN shift_date TEXT DEFAULT '';
ALTER TABLE society_guard_shifts ADD COLUMN actual_start TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN actual_end TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN overtime_minutes INTEGER DEFAULT 0;
ALTER TABLE society_guard_shifts ADD COLUMN notes TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN created_at TEXT;

-- society_intercom_sessions: 9 column(s) absent from a fresh migration
ALTER TABLE society_intercom_sessions ADD COLUMN guard_id TEXT DEFAULT '';
ALTER TABLE society_intercom_sessions ADD COLUMN resident_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE society_intercom_sessions ADD COLUMN call_type TEXT DEFAULT 'voice';
ALTER TABLE society_intercom_sessions ADD COLUMN started_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN answered_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN ended_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN duration_seconds INTEGER DEFAULT 0;
ALTER TABLE society_intercom_sessions ADD COLUMN initiated_by TEXT DEFAULT 'guard';

-- society_invoice_items: 3 column(s) absent from a fresh migration
ALTER TABLE society_invoice_items ADD COLUMN total REAL DEFAULT 0;
ALTER TABLE society_invoice_items ADD COLUMN category TEXT;
ALTER TABLE society_invoice_items ADD COLUMN created_at TEXT;

-- society_ivr_logs: 6 column(s) absent from a fresh migration
ALTER TABLE society_ivr_logs ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_ivr_logs ADD COLUMN resident_phone TEXT;
ALTER TABLE society_ivr_logs ADD COLUMN call_provider TEXT DEFAULT 'msg91';
ALTER TABLE society_ivr_logs ADD COLUMN call_sid TEXT;
ALTER TABLE society_ivr_logs ADD COLUMN call_duration INTEGER DEFAULT 0;
ALTER TABLE society_ivr_logs ADD COLUMN fallback_tier INTEGER DEFAULT 1;

-- society_messages: 5 column(s) absent from a fresh migration
ALTER TABLE society_messages ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_messages ADD COLUMN message TEXT DEFAULT '';
ALTER TABLE society_messages ADD COLUMN message_type TEXT DEFAULT 'text';
ALTER TABLE society_messages ADD COLUMN attachment_url TEXT;
ALTER TABLE society_messages ADD COLUMN read_at TEXT;

-- society_notices: 2 column(s) absent from a fresh migration
ALTER TABLE society_notices ADD COLUMN document_url TEXT;
ALTER TABLE society_notices ADD COLUMN is_urgent INTEGER DEFAULT 0;

-- society_patrol_logs: 8 column(s) absent from a fresh migration
ALTER TABLE society_patrol_logs ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_patrol_logs ADD COLUMN started_at TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN completed_at TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN checkpoints_scanned TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN missed_checkpoints INTEGER DEFAULT 0;
ALTER TABLE society_patrol_logs ADD COLUMN total_checkpoints INTEGER DEFAULT 0;
ALTER TABLE society_patrol_logs ADD COLUMN notes TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN created_at TEXT;

-- society_patrol_routes: 5 column(s) absent from a fresh migration
ALTER TABLE society_patrol_routes ADD COLUMN route_name TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN checkpoints TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN expected_duration_minutes INTEGER DEFAULT 30;
ALTER TABLE society_patrol_routes ADD COLUMN shift TEXT;
ALTER TABLE society_patrol_routes ADD COLUMN is_active INTEGER DEFAULT 1;

-- society_payment_receipts: 7 column(s) absent from a fresh migration
ALTER TABLE society_payment_receipts ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_payment_receipts ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE society_payment_receipts ADD COLUMN amount REAL DEFAULT 0;
ALTER TABLE society_payment_receipts ADD COLUMN payment_method TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN transaction_id TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN receipt_number TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN payment_date TEXT;

-- society_penalty_ledger: 8 column(s) absent from a fresh migration
ALTER TABLE society_penalty_ledger ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_penalty_ledger ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE society_penalty_ledger ADD COLUMN member_id TEXT;
ALTER TABLE society_penalty_ledger ADD COLUMN principal_overdue REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN interest_rate REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN penalty_amount REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN reversal_reason TEXT;
ALTER TABLE society_penalty_ledger ADD COLUMN reversal_date TEXT;

-- society_police_verification: 13 column(s) absent from a fresh migration
ALTER TABLE society_police_verification ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN person_type TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN person_name TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN person_phone TEXT;
ALTER TABLE society_police_verification ADD COLUMN id_proof_type TEXT;
ALTER TABLE society_police_verification ADD COLUMN id_proof_number TEXT;
ALTER TABLE society_police_verification ADD COLUMN id_proof_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN verification_certificate_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN acknowledgment_receipt_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN submitted_to_police_at TEXT;
ALTER TABLE society_police_verification ADD COLUMN verified_at TEXT;
ALTER TABLE society_police_verification ADD COLUMN access_status TEXT DEFAULT 'provisional';

-- society_polls: 1 column(s) absent from a fresh migration
ALTER TABLE society_polls ADD COLUMN question TEXT DEFAULT '';

-- society_settings: 3 column(s) absent from a fresh migration
ALTER TABLE society_settings ADD COLUMN sla_default_hours INTEGER DEFAULT 48;
ALTER TABLE society_settings ADD COLUMN society_letterhead_url TEXT;
ALTER TABLE society_settings ADD COLUMN society_logo_url TEXT;

-- society_staff_payroll: 16 column(s) absent from a fresh migration
ALTER TABLE society_staff_payroll ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_staff_payroll ADD COLUMN vendor_id TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN staff_name TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN total_working_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN present_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN absent_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN late_arrivals INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN overtime_hours REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN per_day_rate REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN deduction_details TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN net_payable REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN payment_status TEXT DEFAULT 'pending';
ALTER TABLE society_staff_payroll ADD COLUMN payment_date TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN payment_reference TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN approved_by TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN created_at TEXT;

-- society_staff_ratings: 4 column(s) absent from a fresh migration
ALTER TABLE society_staff_ratings ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN rated_by TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN month TEXT;

-- society_tally_exports: 5 column(s) absent from a fresh migration
ALTER TABLE society_tally_exports ADD COLUMN payload_xml TEXT;
ALTER TABLE society_tally_exports ADD COLUMN payload_csv TEXT;
ALTER TABLE society_tally_exports ADD COLUMN tally_ledger_mapping TEXT;
ALTER TABLE society_tally_exports ADD COLUMN error_message TEXT;
ALTER TABLE society_tally_exports ADD COLUMN exported_at TEXT;

-- society_utility_deliveries: 11 column(s) absent from a fresh migration
ALTER TABLE society_utility_deliveries ADD COLUMN vehicle_type TEXT DEFAULT '';
ALTER TABLE society_utility_deliveries ADD COLUMN vehicle_number TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN unit TEXT DEFAULT 'liters';
ALTER TABLE society_utility_deliveries ADD COLUMN challan_number TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN cost REAL DEFAULT 0;
ALTER TABLE society_utility_deliveries ADD COLUMN exit_time TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN logged_by TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN verified_by TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN verification_status TEXT DEFAULT 'pending';
ALTER TABLE society_utility_deliveries ADD COLUMN notes TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN created_at TEXT;

-- society_vehicle_log: 10 column(s) absent from a fresh migration
ALTER TABLE society_vehicle_log ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_vehicle_log ADD COLUMN vehicle_type TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN flat_number TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN owner_name TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN direction TEXT DEFAULT '';
ALTER TABLE society_vehicle_log ADD COLUMN guard_id TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN photo_url TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN ocr_confidence REAL;
ALTER TABLE society_vehicle_log ADD COLUMN is_resident_vehicle INTEGER DEFAULT 0;
ALTER TABLE society_vehicle_log ADD COLUMN created_at TEXT;

-- society_vendor_invoices: 13 column(s) absent from a fresh migration
ALTER TABLE society_vendor_invoices ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE society_vendor_invoices ADD COLUMN invoice_number TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN tds_amount REAL DEFAULT 0;
ALTER TABLE society_vendor_invoices ADD COLUMN total REAL DEFAULT 0;
ALTER TABLE society_vendor_invoices ADD COLUMN due_date TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN payment_status TEXT DEFAULT 'pending';
ALTER TABLE society_vendor_invoices ADD COLUMN payment_date TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN payment_reference TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN payment_method TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN invoice_doc_url TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN approved_by TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN notes TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN created_at TEXT;

-- society_vendors: 12 column(s) absent from a fresh migration
ALTER TABLE society_vendors ADD COLUMN vendor_name TEXT DEFAULT '';
ALTER TABLE society_vendors ADD COLUMN contact_person TEXT;
ALTER TABLE society_vendors ADD COLUMN contact_phone TEXT;
ALTER TABLE society_vendors ADD COLUMN contact_email TEXT;
ALTER TABLE society_vendors ADD COLUMN address TEXT;
ALTER TABLE society_vendors ADD COLUMN gst_number TEXT;
ALTER TABLE society_vendors ADD COLUMN pan_number TEXT;
ALTER TABLE society_vendors ADD COLUMN bank_account TEXT;
ALTER TABLE society_vendors ADD COLUMN bank_ifsc TEXT;
ALTER TABLE society_vendors ADD COLUMN payment_terms TEXT;
ALTER TABLE society_vendors ADD COLUMN created_at TEXT;
ALTER TABLE society_vendors ADD COLUMN updated_at TEXT;

-- society_visitor_blacklist: 5 column(s) absent from a fresh migration
ALTER TABLE society_visitor_blacklist ADD COLUMN person_name TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN person_phone TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN person_photo_url TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN blacklisted_by TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN is_active INTEGER DEFAULT 1;

-- society_visitor_preapprovals: 2 column(s) absent from a fresh migration
ALTER TABLE society_visitor_preapprovals ADD COLUMN resident_id TEXT DEFAULT '';
ALTER TABLE society_visitor_preapprovals ADD COLUMN status TEXT DEFAULT 'active';

-- society_visitors: 9 column(s) absent from a fresh migration
ALTER TABLE society_visitors ADD COLUMN guard_id TEXT;
ALTER TABLE society_visitors ADD COLUMN visitor_photo_url TEXT;
ALTER TABLE society_visitors ADD COLUMN id_card_photo_url TEXT;
ALTER TABLE society_visitors ADD COLUMN flat_number TEXT;
ALTER TABLE society_visitors ADD COLUMN approved_at TEXT;
ALTER TABLE society_visitors ADD COLUMN notes TEXT;
ALTER TABLE society_visitors ADD COLUMN expected_time TEXT;
ALTER TABLE society_visitors ADD COLUMN actual_in_time TEXT;
ALTER TABLE society_visitors ADD COLUMN actual_out_time TEXT;

-- vehicles: 6 column(s) absent from a fresh migration
ALTER TABLE vehicles ADD COLUMN owner_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN vehicle_number TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN vehicle_type TEXT;
ALTER TABLE vehicles ADD COLUMN vehicle_photo_url TEXT;
ALTER TABLE vehicles ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE vehicles ADD COLUMN created_at TEXT;

-- admin_roles: 1 column(s) the development database is missing
ALTER TABLE admin_roles ADD COLUMN granted_by TEXT;

-- carpool_live_locations: 1 column(s) the development database is missing
ALTER TABLE carpool_live_locations ADD COLUMN accuracy REAL DEFAULT 0;

-- community_posts: 6 column(s) the development database is missing
ALTER TABLE community_posts ADD COLUMN author_name TEXT DEFAULT '';
ALTER TABLE community_posts ADD COLUMN category TEXT DEFAULT 'general';
ALTER TABLE community_posts ADD COLUMN media_url TEXT;
ALTER TABLE community_posts ADD COLUMN geohash TEXT;
ALTER TABLE community_posts ADD COLUMN likes_count INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN comments_count INTEGER DEFAULT 0;

-- delivery_agents: 1 column(s) the development database is missing
ALTER TABLE delivery_agents ADD COLUMN full_name TEXT;

-- delivery_jobs: 3 column(s) the development database is missing
ALTER TABLE delivery_jobs ADD COLUMN batch_id TEXT;
ALTER TABLE delivery_jobs ADD COLUMN assigned_agent_id TEXT;
ALTER TABLE delivery_jobs ADD COLUMN updated_at DATETIME;

-- employer_job_analytics: 5 column(s) the development database is missing
ALTER TABLE employer_job_analytics ADD COLUMN employer_id TEXT DEFAULT '';
ALTER TABLE employer_job_analytics ADD COLUMN shortlisted INTEGER DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN hired INTEGER DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN avg_match_score REAL DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN top_skills_applied TEXT;

-- feature_flags: 5 column(s) the development database is missing
ALTER TABLE feature_flags ADD COLUMN allowed_pincodes_json TEXT DEFAULT '[]';
ALTER TABLE feature_flags ADD COLUMN title TEXT DEFAULT '';
ALTER TABLE feature_flags ADD COLUMN description TEXT;
ALTER TABLE feature_flags ADD COLUMN coming_soon_headline TEXT;
ALTER TABLE feature_flags ADD COLUMN coming_soon_message TEXT;

-- home_service_bookings: 3 column(s) the development database is missing
ALTER TABLE home_service_bookings ADD COLUMN user_id TEXT DEFAULT '';
ALTER TABLE home_service_bookings ADD COLUMN total_amount REAL;
ALTER TABLE home_service_bookings ADD COLUMN payment_status TEXT DEFAULT 'pending';

-- home_service_providers: 11 column(s) the development database is missing
ALTER TABLE home_service_providers ADD COLUMN shop_id TEXT;
ALTER TABLE home_service_providers ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN phone TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN category_id TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN experience_years INTEGER DEFAULT 1;
ALTER TABLE home_service_providers ADD COLUMN hourly_rate REAL DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN rating REAL DEFAULT 5.0;
ALTER TABLE home_service_providers ADD COLUMN total_jobs INTEGER DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN serviced_pincodes_json TEXT DEFAULT '[]';
ALTER TABLE home_service_providers ADD COLUMN is_verified INTEGER DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN is_available INTEGER DEFAULT 1;

-- job_referrals: 2 column(s) the development database is missing
ALTER TABLE job_referrals ADD COLUMN bounty_paid INTEGER DEFAULT 0;
ALTER TABLE job_referrals ADD COLUMN converted_at DATETIME;

-- job_skill_assessments: 1 column(s) the development database is missing
ALTER TABLE job_skill_assessments ADD COLUMN difficulty TEXT DEFAULT 'intermediate';

-- job_walkin_events: 5 column(s) the development database is missing
ALTER TABLE job_walkin_events ADD COLUMN latitude REAL;
ALTER TABLE job_walkin_events ADD COLUMN longitude REAL;
ALTER TABLE job_walkin_events ADD COLUMN positions_available TEXT;
ALTER TABLE job_walkin_events ADD COLUMN max_candidates INTEGER DEFAULT 50;
ALTER TABLE job_walkin_events ADD COLUMN registered_count INTEGER DEFAULT 0;

-- local_job_postings: 9 column(s) the development database is missing
ALTER TABLE local_job_postings ADD COLUMN employer_id TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN category TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN salary_range TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN job_type TEXT DEFAULT 'Full-Time';
ALTER TABLE local_job_postings ADD COLUMN address TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN latitude REAL;
ALTER TABLE local_job_postings ADD COLUMN longitude REAL;
ALTER TABLE local_job_postings ADD COLUMN geohash TEXT;
ALTER TABLE local_job_postings ADD COLUMN requirements TEXT;

-- local_property_listings: 2 column(s) the development database is missing
ALTER TABLE local_property_listings ADD COLUMN geohash TEXT;
ALTER TABLE local_property_listings ADD COLUMN is_verified INTEGER DEFAULT 0;

-- local_shops: 2 column(s) the development database is missing
ALTER TABLE local_shops ADD COLUMN phone_number TEXT;
ALTER TABLE local_shops ADD COLUMN coordinate TEXT DEFAULT '';

-- loyalty_transactions: 3 column(s) the development database is missing
ALTER TABLE loyalty_transactions ADD COLUMN transaction_type TEXT DEFAULT '';
ALTER TABLE loyalty_transactions ADD COLUMN reference_id TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN description TEXT;

-- marketplace_auctions: 1 column(s) the development database is missing
ALTER TABLE marketplace_auctions ADD COLUMN starts_at DATETIME;

-- marketplace_escrow: 5 column(s) the development database is missing
ALTER TABLE marketplace_escrow ADD COLUMN razorpay_payment_id TEXT;
ALTER TABLE marketplace_escrow ADD COLUMN razorpay_order_id TEXT;
ALTER TABLE marketplace_escrow ADD COLUMN held_at DATETIME;
ALTER TABLE marketplace_escrow ADD COLUMN refunded_at DATETIME;
ALTER TABLE marketplace_escrow ADD COLUMN resolved_at DATETIME;

-- marketplace_seller_scores: 4 column(s) the development database is missing
ALTER TABLE marketplace_seller_scores ADD COLUMN verified_email INTEGER DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN verified_id INTEGER DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN avg_rating REAL DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN avg_response_time_mins REAL DEFAULT 0;

-- medical_providers: 4 column(s) the development database is missing
ALTER TABLE medical_providers ADD COLUMN provider_name TEXT DEFAULT '';
ALTER TABLE medical_providers ADD COLUMN license_no TEXT;
ALTER TABLE medical_providers ADD COLUMN zone TEXT;
ALTER TABLE medical_providers ADD COLUMN is_verified INTEGER DEFAULT 0;

-- move_passes: 4 column(s) the development database is missing
ALTER TABLE move_passes ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN type TEXT;
ALTER TABLE move_passes ADD COLUMN status TEXT DEFAULT 'pending';
ALTER TABLE move_passes ADD COLUMN moving_date TEXT;

-- platform_settings: 1 column(s) the development database is missing
ALTER TABLE platform_settings ADD COLUMN updated_at TEXT;

-- shop_categories: 5 column(s) the development database is missing
ALTER TABLE shop_categories ADD COLUMN business_model TEXT DEFAULT '';
ALTER TABLE shop_categories ADD COLUMN commission_percent REAL DEFAULT 5.0;
ALTER TABLE shop_categories ADD COLUMN convenience_fee REAL DEFAULT 0.0;
ALTER TABLE shop_categories ADD COLUMN registration_fields TEXT DEFAULT '[]';
ALTER TABLE shop_categories ADD COLUMN updated_at TEXT;

-- shop_orders: 3 column(s) the development database is missing
ALTER TABLE shop_orders ADD COLUMN user_id TEXT;
ALTER TABLE shop_orders ADD COLUMN items TEXT DEFAULT '';
ALTER TABLE shop_orders ADD COLUMN payment_method TEXT;

-- shop_products: 1 column(s) the development database is missing
ALTER TABLE shop_products ADD COLUMN updated_at TEXT;

-- shop_qa: 2 column(s) the development database is missing
ALTER TABLE shop_qa ADD COLUMN answered_by TEXT;
ALTER TABLE shop_qa ADD COLUMN updated_at TEXT;

-- society_advance_account: 1 column(s) the development database is missing
ALTER TABLE society_advance_account ADD COLUMN updated_at DATETIME;

-- society_agm_minutes: 1 column(s) the development database is missing
ALTER TABLE society_agm_minutes ADD COLUMN published_by TEXT;

-- society_amenities: 7 column(s) the development database is missing
ALTER TABLE society_amenities ADD COLUMN capacity INTEGER;
ALTER TABLE society_amenities ADD COLUMN hourly_rate REAL DEFAULT 0;
ALTER TABLE society_amenities ADD COLUMN booking_advance_days INTEGER DEFAULT 7;
ALTER TABLE society_amenities ADD COLUMN available_from TEXT DEFAULT '06:00';
ALTER TABLE society_amenities ADD COLUMN available_until TEXT DEFAULT '22:00';
ALTER TABLE society_amenities ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE society_amenities ADD COLUMN rules TEXT;

-- society_amenity_locks: 1 column(s) the development database is missing
ALTER TABLE society_amenity_locks ADD COLUMN flat_number TEXT DEFAULT '';

-- society_asset_maintenance_log: 3 column(s) the development database is missing
ALTER TABLE society_asset_maintenance_log ADD COLUMN service_type TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN service_date DATETIME;
ALTER TABLE society_asset_maintenance_log ADD COLUMN notes TEXT;

-- society_assets: 3 column(s) the development database is missing
ALTER TABLE society_assets ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE society_assets ADD COLUMN category TEXT;
ALTER TABLE society_assets ADD COLUMN amc_expiry DATETIME;

-- society_billing_config: 2 column(s) the development database is missing
ALTER TABLE society_billing_config ADD COLUMN sinking_fund_rate_percent REAL;
ALTER TABLE society_billing_config ADD COLUMN late_penalty_rate_percent REAL DEFAULT 21;

-- society_budget: 2 column(s) the development database is missing
ALTER TABLE society_budget ADD COLUMN year TEXT DEFAULT '';
ALTER TABLE society_budget ADD COLUMN total_amount REAL;

-- society_budget_items: 2 column(s) the development database is missing
ALTER TABLE society_budget_items ADD COLUMN allocated_amount REAL;
ALTER TABLE society_budget_items ADD COLUMN spent_amount REAL DEFAULT 0;

-- society_charge_heads: 1 column(s) the development database is missing
ALTER TABLE society_charge_heads ADD COLUMN gst_applicable INTEGER DEFAULT 0;

-- society_complaint_activity: 3 column(s) the development database is missing
ALTER TABLE society_complaint_activity ADD COLUMN old_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN new_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN changed_by TEXT;

-- society_delivery_preferences: 3 column(s) the development database is missing
ALTER TABLE society_delivery_preferences ADD COLUMN leave_at_gate INTEGER DEFAULT 0;
ALTER TABLE society_delivery_preferences ADD COLUMN preferred_window TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN package_location TEXT;

-- society_document_templates: 2 column(s) the development database is missing
ALTER TABLE society_document_templates ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN content TEXT DEFAULT '';

-- society_emergency_alerts: 3 column(s) the development database is missing
ALTER TABLE society_emergency_alerts ADD COLUMN description TEXT;
ALTER TABLE society_emergency_alerts ADD COLUMN flat_number TEXT;
ALTER TABLE society_emergency_alerts ADD COLUMN resolved_at TEXT;

-- society_fire_safety: 2 column(s) the development database is missing
ALTER TABLE society_fire_safety ADD COLUMN last_inspection DATETIME;
ALTER TABLE society_fire_safety ADD COLUMN next_due DATETIME;

-- society_flat_ledger: 2 column(s) the development database is missing
ALTER TABLE society_flat_ledger ADD COLUMN carpet_area REAL;
ALTER TABLE society_flat_ledger ADD COLUMN outstanding_balance REAL DEFAULT 0;

-- society_forum_replies: 1 column(s) the development database is missing
ALTER TABLE society_forum_replies ADD COLUMN likes INTEGER DEFAULT 0;

-- society_forum_topics: 1 column(s) the development database is missing
ALTER TABLE society_forum_topics ADD COLUMN author_id TEXT DEFAULT '';

-- society_gates: 1 column(s) the development database is missing
ALTER TABLE society_gates ADD COLUMN name TEXT DEFAULT '';

-- society_guard_shift_swaps: 3 column(s) the development database is missing
ALTER TABLE society_guard_shift_swaps ADD COLUMN shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN requested_by TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN requested_with TEXT;

-- society_guard_shifts: 1 column(s) the development database is missing
ALTER TABLE society_guard_shifts ADD COLUMN shift_name TEXT;

-- society_intercom_sessions: 3 column(s) the development database is missing
ALTER TABLE society_intercom_sessions ADD COLUMN caller_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN receiver_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN duration INTEGER DEFAULT 0;

-- society_ivr_logs: 1 column(s) the development database is missing
ALTER TABLE society_ivr_logs ADD COLUMN phone_called TEXT DEFAULT '';

-- society_members: 3 column(s) the development database is missing
ALTER TABLE society_members ADD COLUMN role TEXT DEFAULT 'resident';
ALTER TABLE society_members ADD COLUMN is_active INTEGER DEFAULT 1;
ALTER TABLE society_members ADD COLUMN added_by TEXT;

-- society_messages: 1 column(s) the development database is missing
ALTER TABLE society_messages ADD COLUMN content TEXT DEFAULT '';

-- society_notices: 2 column(s) the development database is missing
ALTER TABLE society_notices ADD COLUMN priority TEXT DEFAULT 'normal';
ALTER TABLE society_notices ADD COLUMN is_active INTEGER DEFAULT 1;

-- society_patrol_logs: 4 column(s) the development database is missing
ALTER TABLE society_patrol_logs ADD COLUMN start_time DATETIME;
ALTER TABLE society_patrol_logs ADD COLUMN end_time DATETIME;
ALTER TABLE society_patrol_logs ADD COLUMN scanned_checkpoints_json TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN completion_percent REAL;

-- society_patrol_routes: 2 column(s) the development database is missing
ALTER TABLE society_patrol_routes ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN checkpoints_json TEXT DEFAULT '';

-- society_payment_receipts: 3 column(s) the development database is missing
ALTER TABLE society_payment_receipts ADD COLUMN amount_paid REAL DEFAULT 0;
ALTER TABLE society_payment_receipts ADD COLUMN payment_mode TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN transaction_ref TEXT;

-- society_penalty_ledger: 2 column(s) the development database is missing
ALTER TABLE society_penalty_ledger ADD COLUMN amount REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN reverse_reason TEXT;

-- society_police_verification: 2 column(s) the development database is missing
ALTER TABLE society_police_verification ADD COLUMN member_id TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN document_url TEXT DEFAULT '';

-- society_polls: 7 column(s) the development database is missing
ALTER TABLE society_polls ADD COLUMN title TEXT DEFAULT '';
ALTER TABLE society_polls ADD COLUMN description TEXT;
ALTER TABLE society_polls ADD COLUMN poll_type TEXT DEFAULT 'single';
ALTER TABLE society_polls ADD COLUMN is_anonymous INTEGER DEFAULT 0;
ALTER TABLE society_polls ADD COLUMN starts_at TEXT;
ALTER TABLE society_polls ADD COLUMN ends_at TEXT;
ALTER TABLE society_polls ADD COLUMN status TEXT DEFAULT 'active';

-- society_settings: 9 column(s) the development database is missing
ALTER TABLE society_settings ADD COLUMN auto_approve_expected INTEGER DEFAULT 0;
ALTER TABLE society_settings ADD COLUMN visitor_photo_required INTEGER DEFAULT 1;
ALTER TABLE society_settings ADD COLUMN id_card_required INTEGER DEFAULT 1;
ALTER TABLE society_settings ADD COLUMN max_visitors_per_flat INTEGER DEFAULT 10;
ALTER TABLE society_settings ADD COLUMN guard_shift_start TEXT DEFAULT '06:00';
ALTER TABLE society_settings ADD COLUMN guard_shift_end TEXT DEFAULT '22:00';
ALTER TABLE society_settings ADD COLUMN maintenance_due_day INTEGER DEFAULT 5;
ALTER TABLE society_settings ADD COLUMN late_fee_percentage REAL DEFAULT 5.0;
ALTER TABLE society_settings ADD COLUMN updated_at TEXT;

-- society_staff_attendance: 3 column(s) the development database is missing
ALTER TABLE society_staff_attendance ADD COLUMN marked_by TEXT;
ALTER TABLE society_staff_attendance ADD COLUMN status TEXT DEFAULT 'present';
ALTER TABLE society_staff_attendance ADD COLUMN notes TEXT;

-- society_staff_payroll: 2 column(s) the development database is missing
ALTER TABLE society_staff_payroll ADD COLUMN net_salary REAL;
ALTER TABLE society_staff_payroll ADD COLUMN status TEXT DEFAULT 'pending';

-- society_staff_ratings: 1 column(s) the development database is missing
ALTER TABLE society_staff_ratings ADD COLUMN member_id TEXT DEFAULT '';

-- society_tally_exports: 1 column(s) the development database is missing
ALTER TABLE society_tally_exports ADD COLUMN xml_payload TEXT;

-- society_utility_deliveries: 2 column(s) the development database is missing
ALTER TABLE society_utility_deliveries ADD COLUMN gate_id TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN utility_type TEXT;

-- society_vehicle_log: 4 column(s) the development database is missing
ALTER TABLE society_vehicle_log ADD COLUMN entry_time DATETIME;
ALTER TABLE society_vehicle_log ADD COLUMN exit_time DATETIME;
ALTER TABLE society_vehicle_log ADD COLUMN vehicle_photo_url TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN status TEXT DEFAULT 'entered';

-- society_vendor_invoices: 2 column(s) the development database is missing
ALTER TABLE society_vendor_invoices ADD COLUMN status TEXT DEFAULT 'pending';
ALTER TABLE society_vendor_invoices ADD COLUMN payment_ref TEXT;

-- society_vendors: 1 column(s) the development database is missing
ALTER TABLE society_vendors ADD COLUMN name TEXT DEFAULT '';

-- society_visitor_blacklist: 3 column(s) the development database is missing
ALTER TABLE society_visitor_blacklist ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN phone TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN added_by TEXT;

-- society_visitor_preapprovals: 1 column(s) the development database is missing
ALTER TABLE society_visitor_preapprovals ADD COLUMN is_revoked INTEGER DEFAULT 0;

-- users: 5 column(s) the development database is missing
ALTER TABLE users ADD COLUMN email_verified INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN whatsapp_number TEXT;
ALTER TABLE users ADD COLUMN auth_method TEXT DEFAULT 'phone_otp';
ALTER TABLE users ADD COLUMN last_login_at TEXT;
ALTER TABLE users ADD COLUMN login_count INTEGER DEFAULT 0;

-- vehicles: 7 column(s) the development database is missing
ALTER TABLE vehicles ADD COLUMN society_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN user_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN flat_number TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN license_plate TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN make_model TEXT;
ALTER TABLE vehicles ADD COLUMN parking_slot TEXT;
ALTER TABLE vehicles ADD COLUMN rfid_tag_id TEXT;

-- --------------------------------------------------------------------------
-- Tables that ALTER cannot repair
-- --------------------------------------------------------------------------

-- equipment_listings: no migration creates this table at all.
CREATE TABLE IF NOT EXISTS equipment_listings (
        id INTEGER PRIMARY KEY,
        owner_id INTEGER,
        item_name TEXT,
        category TEXT,
        daily_price INTEGER,
        security_deposit INTEGER,
        status TEXT
      );

-- loyalty_wallets: no migration creates this table at all.
CREATE TABLE IF NOT EXISTS loyalty_wallets (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER REFERENCES users(id) UNIQUE,
      total_coins INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );

-- volunteer_tasks: no migration creates this table at all.
CREATE TABLE IF NOT EXISTS volunteer_tasks (
        id INTEGER PRIMARY KEY,
        poster_id INTEGER,
        title TEXT,
        bounty_coins INTEGER,
        type TEXT,
        status TEXT,
        volunteer_id INTEGER
      );
