-- Migration 076: restore columns lost to duplicate CREATE TABLE declarations
--
-- Several tables are declared twice with CREATE TABLE IF NOT EXISTS: once as an
-- early stub and once, later, in full. Migrations run in filename order, so on a
-- fresh database the stub wins and the full declaration silently does nothing.
-- society_assets is the clearest case -- a new deployment gets 7 columns with a
-- `name`, while the application queries `asset_name` against 23.
--
-- The development database was built before the migrations reached their current
-- order, so it has the full tables. That is precisely why this went unnoticed:
-- the only database anyone inspects is the one that happens to be correct, while
-- every genuinely new environment -- CI, staging, production -- would get stubs.
--
-- These statements were generated by diffing a freshly-migrated database against
-- the live one (scripts/generate-fresh-parity-migration.js), not written by hand,
-- so the column list is measured rather than remembered.
--
-- On the development database every statement here is a no-op.


-- community_posts: 4 column(s) absent from a fresh migration
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'discussion';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS comments INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS is_pinned INTEGER DEFAULT 0;

-- delivery_jobs: 1 column(s) absent from a fresh migration
ALTER TABLE delivery_jobs ADD COLUMN IF NOT EXISTS agent_id INTEGER;

-- feature_flags: 2 column(s) absent from a fresh migration
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- franchise_partners: 9 column(s) absent from a fresh migration
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS product_commission_percent REAL DEFAULT 5.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS skilled_job_commission_percent REAL DEFAULT 10.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS event_ticket_commission_percent REAL DEFAULT 5.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS delivery_base_fee REAL DEFAULT 20.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS property_listing_fee REAL DEFAULT 500.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS marketplace_listing_fee REAL DEFAULT 50.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS platform_profit_split REAL DEFAULT 60.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS reward_pool_split REAL DEFAULT 20.0;
ALTER TABLE franchise_partners ADD COLUMN IF NOT EXISTS reserve_split REAL DEFAULT 20.0;

-- home_service_bookings: 3 column(s) absent from a fresh migration
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS customer_id INTEGER;
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS service_type TEXT;
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS is_payout_settled INTEGER DEFAULT 0;

-- home_service_providers: 2 column(s) absent from a fresh migration
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS service_type TEXT;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS wallet_balance REAL DEFAULT 0;

-- job_walkin_events: 4 column(s) absent from a fresh migration
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS lat REAL;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS lng REAL;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS positions TEXT;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS salary_range TEXT;

-- local_job_postings: 4 column(s) absent from a fresh migration
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS shop_id TEXT;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS salary REAL;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- local_shops: 4 column(s) absent from a fresh migration
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS pincode TEXT;
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS rating REAL DEFAULT 0;
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS is_featured INTEGER DEFAULT 0;

-- localization_dictionaries: 1 column(s) absent from a fresh migration
ALTER TABLE localization_dictionaries ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- loyalty_transactions: 2 column(s) absent from a fresh migration
ALTER TABLE loyalty_transactions ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN IF NOT EXISTS source TEXT;

-- marketplace_auctions: 1 column(s) absent from a fresh migration
ALTER TABLE marketplace_auctions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- marketplace_escrow: 1 column(s) absent from a fresh migration
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- medical_providers: 3 column(s) absent from a fresh migration
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS contact_number TEXT;

-- move_passes: 13 column(s) absent from a fresh migration
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS requested_by TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS flat_owner_id TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS move_type TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS move_date TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS clearance_status TEXT DEFAULT 'pending';
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS outstanding_dues REAL DEFAULT 0;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS gate_passcode TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS movers_company TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS movers_vehicle_number TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS admin_approved_at TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS admin_approved_by TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- shop_categories: 14 column(s) absent from a fresh migration
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS name_mr TEXT;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS name_hi TEXT;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS archetype TEXT DEFAULT 'retail';
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS parent_category_id TEXT;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS requires_fssai INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS requires_gst INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS requires_drug_license INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS supports_delivery INTEGER DEFAULT 1;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS supports_pickup INTEGER DEFAULT 1;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS supports_appointment INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS supports_subscription INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS supports_table_booking INTEGER DEFAULT 0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS default_commission_pct REAL DEFAULT 10.0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS min_order_amount REAL DEFAULT 0;

-- shop_orders: 2 column(s) absent from a fresh migration
ALTER TABLE shop_orders ADD COLUMN IF NOT EXISTS customer_id INTEGER;
ALTER TABLE shop_orders ADD COLUMN IF NOT EXISTS payment_gateway_ref TEXT;

-- shop_products: 3 column(s) absent from a fresh migration
ALTER TABLE shop_products ADD COLUMN IF NOT EXISTS mrp REAL;
ALTER TABLE shop_products ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0;
ALTER TABLE shop_products ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;

-- society_admin_roles: 4 column(s) absent from a fresh migration
ALTER TABLE society_admin_roles ADD COLUMN IF NOT EXISTS appointed_at TEXT;
ALTER TABLE society_admin_roles ADD COLUMN IF NOT EXISTS appointed_by TEXT;
ALTER TABLE society_admin_roles ADD COLUMN IF NOT EXISTS expires_at TEXT;
ALTER TABLE society_admin_roles ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_advance_account: 6 column(s) absent from a fresh migration
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS member_id TEXT DEFAULT '';
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS credit_amount REAL DEFAULT 0;
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS utilized_amount REAL DEFAULT 0;
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS reference_bill_id TEXT;
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_agm_meetings: 7 column(s) absent from a fresh migration
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS meeting_type TEXT DEFAULT '';
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS start_time TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS end_time TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS attendees_count INTEGER DEFAULT 0;
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE society_agm_meetings ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_agm_minutes: 6 column(s) absent from a fresh migration
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS resolutions TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS attendees TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS recorded_by TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS published_at TEXT;
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS document_url TEXT;

-- society_amenity_locks: 5 column(s) absent from a fresh migration
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS booking_date TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS start_time TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS end_time TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS locked_by TEXT DEFAULT '';
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_asset_maintenance_log: 10 column(s) absent from a fresh migration
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS maintenance_type TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS performed_by TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS vendor_id TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS parts_replaced TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS performed_at TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS next_due TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS photo_urls TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_assets: 19 column(s) absent from a fresh migration
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS asset_name TEXT DEFAULT '';
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS asset_type TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS asset_code TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS make_model TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS purchase_date TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS purchase_cost REAL DEFAULT 0;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS installation_date TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS warranty_expiry TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS amc_start_date TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS amc_end_date TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS amc_cost REAL DEFAULT 0;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS last_serviced_at TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS next_service_due TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_billing_config: 11 column(s) absent from a fresh migration
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS sinking_fund_rate REAL DEFAULT 0.25;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS max_late_interest_rate REAL DEFAULT 21.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS actual_late_interest_rate REAL DEFAULT 18.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS noc_percentage REAL DEFAULT 10.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS grace_period_days INTEGER DEFAULT 15;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS gst_rate REAL DEFAULT 18.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS tds_enabled INTEGER DEFAULT 0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS tds_rate REAL DEFAULT 2.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS parking_charge_two_wheeler REAL DEFAULT 200.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS parking_charge_four_wheeler REAL DEFAULT 500.0;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_budget: 7 column(s) absent from a fresh migration
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS financial_year TEXT DEFAULT '';
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS total_budget REAL DEFAULT 0;
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS total_income_projected REAL DEFAULT 0;
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS notes TEXT;

-- society_budget_items: 5 column(s) absent from a fresh migration
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS budgeted_amount REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS actual_amount REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS variance REAL DEFAULT 0;
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_cab_preapprovals: 3 column(s) absent from a fresh migration
ALTER TABLE society_cab_preapprovals ADD COLUMN IF NOT EXISTS resident_id TEXT DEFAULT '';
ALTER TABLE society_cab_preapprovals ADD COLUMN IF NOT EXISTS vehicle_number TEXT;
ALTER TABLE society_cab_preapprovals ADD COLUMN IF NOT EXISTS used_at TEXT;

-- society_charge_heads: 5 column(s) absent from a fresh migration
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS formula TEXT;
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS is_gst_applicable INTEGER DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS gst_rate REAL DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_complaint_activity: 6 column(s) absent from a fresh migration
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS society_id TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS action TEXT DEFAULT '';
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS from_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS to_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS performed_by TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS performer_name TEXT;

-- society_delivery_preferences: 8 column(s) absent from a fresh migration
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS member_id TEXT DEFAULT '';
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS preferred_window_start TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS preferred_window_end TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS default_leave_at_gate INTEGER DEFAULT 0;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS preferred_package_location TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS special_instructions TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_document_templates: 6 column(s) absent from a fresh migration
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS template_name TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS template_type TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS template_content TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS variables TEXT;
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_emergency_alerts: 1 column(s) absent from a fresh migration
ALTER TABLE society_emergency_alerts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- society_expense_categories: 4 column(s) absent from a fresh migration
ALTER TABLE society_expense_categories ADD COLUMN IF NOT EXISTS parent_category TEXT;
ALTER TABLE society_expense_categories ADD COLUMN IF NOT EXISTS budget_amount REAL DEFAULT 0;
ALTER TABLE society_expense_categories ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
ALTER TABLE society_expense_categories ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_fire_safety: 11 column(s) absent from a fresh migration
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS equipment_name TEXT DEFAULT '';
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS last_inspection_date TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS next_inspection_due TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS inspection_vendor TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS noc_number TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS noc_expiry TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_flat_ledger: 12 column(s) absent from a fresh migration
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS member_id TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS carpet_area_sqft REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS construction_cost REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS advance_balance REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS total_arrears REAL DEFAULT 0;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS tenant_name TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS tenant_phone TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS tenant_lease_start TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS police_verification_status TEXT DEFAULT 'not_required';
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS police_verification_doc_url TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS police_verification_expiry TEXT;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_forum_replies: 4 column(s) absent from a fresh migration
ALTER TABLE society_forum_replies ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_replies ADD COLUMN IF NOT EXISTS liked_by TEXT DEFAULT '[]';
ALTER TABLE society_forum_replies ADD COLUMN IF NOT EXISTS is_edited INTEGER DEFAULT 0;
ALTER TABLE society_forum_replies ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_forum_topics: 6 column(s) absent from a fresh migration
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT '';
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS reply_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS last_reply_at TEXT;
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS last_reply_by TEXT;
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_gates: 5 column(s) absent from a fresh migration
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS gate_name TEXT DEFAULT '';
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS gate_type TEXT DEFAULT 'main';
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS location_description TEXT;
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS assigned_guards TEXT;
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_guard_reminders: 1 column(s) absent from a fresh migration
ALTER TABLE society_guard_reminders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- society_guard_shift_swaps: 9 column(s) absent from a fresh migration
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS requester_guard_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS target_guard_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS requester_shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS target_shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_guard_shifts: 7 column(s) absent from a fresh migration
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS shift_type TEXT DEFAULT '';
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS shift_date TEXT DEFAULT '';
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS actual_start TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS actual_end TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS overtime_minutes INTEGER DEFAULT 0;
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_intercom_sessions: 9 column(s) absent from a fresh migration
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS guard_id TEXT DEFAULT '';
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS resident_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS call_type TEXT DEFAULT 'voice';
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS answered_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS ended_at TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS duration_seconds INTEGER DEFAULT 0;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS initiated_by TEXT DEFAULT 'guard';

-- society_invoice_items: 3 column(s) absent from a fresh migration
ALTER TABLE society_invoice_items ADD COLUMN IF NOT EXISTS total REAL DEFAULT 0;
ALTER TABLE society_invoice_items ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE society_invoice_items ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_ivr_logs: 6 column(s) absent from a fresh migration
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS resident_phone TEXT;
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS call_provider TEXT DEFAULT 'msg91';
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS call_sid TEXT;
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS call_duration INTEGER DEFAULT 0;
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS fallback_tier INTEGER DEFAULT 1;

-- society_messages: 5 column(s) absent from a fresh migration
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS message TEXT DEFAULT '';
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS message_type TEXT DEFAULT 'text';
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS read_at TEXT;

-- society_notices: 2 column(s) absent from a fresh migration
ALTER TABLE society_notices ADD COLUMN IF NOT EXISTS document_url TEXT;
ALTER TABLE society_notices ADD COLUMN IF NOT EXISTS is_urgent INTEGER DEFAULT 0;

-- society_patrol_logs: 8 column(s) absent from a fresh migration
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS completed_at TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS checkpoints_scanned TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS missed_checkpoints INTEGER DEFAULT 0;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS total_checkpoints INTEGER DEFAULT 0;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_patrol_routes: 5 column(s) absent from a fresh migration
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS route_name TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS checkpoints TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS expected_duration_minutes INTEGER DEFAULT 30;
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS shift TEXT;
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;

-- society_payment_receipts: 7 column(s) absent from a fresh migration
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS amount REAL DEFAULT 0;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS transaction_id TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS receipt_number TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS payment_date TEXT;

-- society_penalty_ledger: 8 column(s) absent from a fresh migration
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS member_id TEXT;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS principal_overdue REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS interest_rate REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS penalty_amount REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS reversal_reason TEXT;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS reversal_date TEXT;

-- society_police_verification: 13 column(s) absent from a fresh migration
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS person_type TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS person_name TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS person_phone TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS id_proof_type TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS id_proof_number TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS id_proof_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS verification_certificate_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS acknowledgment_receipt_url TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS submitted_to_police_at TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS verified_at TEXT;
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS access_status TEXT DEFAULT 'provisional';

-- society_polls: 1 column(s) absent from a fresh migration
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS question TEXT DEFAULT '';

-- society_settings: 3 column(s) absent from a fresh migration
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS sla_default_hours INTEGER DEFAULT 48;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS society_letterhead_url TEXT;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS society_logo_url TEXT;

-- society_staff_payroll: 16 column(s) absent from a fresh migration
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS vendor_id TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS staff_name TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS total_working_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS present_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS absent_days INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS late_arrivals INTEGER DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS overtime_hours REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS per_day_rate REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS deduction_details TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS net_payable REAL DEFAULT 0;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS payment_date TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS payment_reference TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_staff_ratings: 4 column(s) absent from a fresh migration
ALTER TABLE society_staff_ratings ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN IF NOT EXISTS rated_by TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE society_staff_ratings ADD COLUMN IF NOT EXISTS month TEXT;

-- society_tally_exports: 5 column(s) absent from a fresh migration
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS payload_xml TEXT;
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS payload_csv TEXT;
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS tally_ledger_mapping TEXT;
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS exported_at TEXT;

-- society_utility_deliveries: 11 column(s) absent from a fresh migration
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS vehicle_type TEXT DEFAULT '';
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS vehicle_number TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'liters';
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS challan_number TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS cost REAL DEFAULT 0;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS exit_time TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS logged_by TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS verified_by TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'pending';
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_vehicle_log: 10 column(s) absent from a fresh migration
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS vehicle_type TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS flat_number TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS owner_name TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS direction TEXT DEFAULT '';
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS guard_id TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS ocr_confidence REAL;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS is_resident_vehicle INTEGER DEFAULT 0;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_vendor_invoices: 13 column(s) absent from a fresh migration
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS invoice_number TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS tds_amount REAL DEFAULT 0;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS total REAL DEFAULT 0;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS due_date TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS payment_date TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS payment_reference TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS invoice_doc_url TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_vendors: 12 column(s) absent from a fresh migration
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS vendor_name TEXT DEFAULT '';
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS contact_person TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS gst_number TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS pan_number TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS bank_account TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS bank_ifsc TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS payment_terms TEXT;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_visitor_blacklist: 5 column(s) absent from a fresh migration
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS person_name TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS person_phone TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS person_photo_url TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS blacklisted_by TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;

-- society_visitor_preapprovals: 2 column(s) absent from a fresh migration
ALTER TABLE society_visitor_preapprovals ADD COLUMN IF NOT EXISTS resident_id TEXT DEFAULT '';
ALTER TABLE society_visitor_preapprovals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- society_visitors: 9 column(s) absent from a fresh migration
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS guard_id TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS visitor_photo_url TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS id_card_photo_url TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS flat_number TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS approved_at TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS expected_time TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS actual_in_time TEXT;
ALTER TABLE society_visitors ADD COLUMN IF NOT EXISTS actual_out_time TEXT;

-- vehicles: 6 column(s) absent from a fresh migration
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS owner_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_number TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_type TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_photo_url TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS created_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- admin_roles: 1 column(s) the development database is missing
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS granted_by TEXT;

-- carpool_live_locations: 1 column(s) the development database is missing
ALTER TABLE carpool_live_locations ADD COLUMN IF NOT EXISTS accuracy REAL DEFAULT 0;

-- community_posts: 6 column(s) the development database is missing
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS author_name TEXT DEFAULT '';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'general';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS media_url TEXT;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS geohash TEXT;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS comments_count INTEGER DEFAULT 0;

-- delivery_agents: 1 column(s) the development database is missing
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS full_name TEXT;

-- delivery_jobs: 3 column(s) the development database is missing
ALTER TABLE delivery_jobs ADD COLUMN IF NOT EXISTS batch_id TEXT;
ALTER TABLE delivery_jobs ADD COLUMN IF NOT EXISTS assigned_agent_id TEXT;
ALTER TABLE delivery_jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- employer_job_analytics: 5 column(s) the development database is missing
ALTER TABLE employer_job_analytics ADD COLUMN IF NOT EXISTS employer_id TEXT DEFAULT '';
ALTER TABLE employer_job_analytics ADD COLUMN IF NOT EXISTS shortlisted INTEGER DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN IF NOT EXISTS hired INTEGER DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN IF NOT EXISTS avg_match_score REAL DEFAULT 0;
ALTER TABLE employer_job_analytics ADD COLUMN IF NOT EXISTS top_skills_applied TEXT;

-- feature_flags: 5 column(s) the development database is missing
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS allowed_pincodes_json TEXT DEFAULT '[]';
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS title TEXT DEFAULT '';
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS coming_soon_headline TEXT;
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS coming_soon_message TEXT;

-- home_service_bookings: 3 column(s) the development database is missing
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS user_id TEXT DEFAULT '';
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS total_amount REAL;
ALTER TABLE home_service_bookings ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';

-- home_service_providers: 11 column(s) the development database is missing
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS shop_id TEXT;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS category_id TEXT DEFAULT '';
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 1;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS hourly_rate REAL DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS rating REAL DEFAULT 5.0;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS total_jobs INTEGER DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS serviced_pincodes_json TEXT DEFAULT '[]';
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS is_verified INTEGER DEFAULT 0;
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS is_available INTEGER DEFAULT 1;

-- job_referrals: 2 column(s) the development database is missing
ALTER TABLE job_referrals ADD COLUMN IF NOT EXISTS bounty_paid INTEGER DEFAULT 0;
ALTER TABLE job_referrals ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ;

-- job_skill_assessments: 1 column(s) the development database is missing
ALTER TABLE job_skill_assessments ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'intermediate';

-- job_walkin_events: 5 column(s) the development database is missing
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS latitude REAL;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS longitude REAL;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS positions_available TEXT;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS max_candidates INTEGER DEFAULT 50;
ALTER TABLE job_walkin_events ADD COLUMN IF NOT EXISTS registered_count INTEGER DEFAULT 0;

-- local_job_postings: 9 column(s) the development database is missing
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS employer_id TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS salary_range TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS job_type TEXT DEFAULT 'Full-Time';
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS latitude REAL;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS longitude REAL;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS geohash TEXT;
ALTER TABLE local_job_postings ADD COLUMN IF NOT EXISTS requirements TEXT;

-- local_property_listings: 2 column(s) the development database is missing
ALTER TABLE local_property_listings ADD COLUMN IF NOT EXISTS geohash TEXT;
ALTER TABLE local_property_listings ADD COLUMN IF NOT EXISTS is_verified INTEGER DEFAULT 0;

-- local_shops: 2 column(s) the development database is missing
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE local_shops ADD COLUMN IF NOT EXISTS coordinate TEXT DEFAULT '';

-- loyalty_transactions: 3 column(s) the development database is missing
ALTER TABLE loyalty_transactions ADD COLUMN IF NOT EXISTS transaction_type TEXT DEFAULT '';
ALTER TABLE loyalty_transactions ADD COLUMN IF NOT EXISTS reference_id TEXT;
ALTER TABLE loyalty_transactions ADD COLUMN IF NOT EXISTS description TEXT;

-- marketplace_auctions: 1 column(s) the development database is missing
ALTER TABLE marketplace_auctions ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- marketplace_escrow: 5 column(s) the development database is missing
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS razorpay_payment_id TEXT;
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS razorpay_order_id TEXT;
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS held_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;
ALTER TABLE marketplace_escrow ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

-- marketplace_seller_scores: 4 column(s) the development database is missing
ALTER TABLE marketplace_seller_scores ADD COLUMN IF NOT EXISTS verified_email INTEGER DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN IF NOT EXISTS verified_id INTEGER DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN IF NOT EXISTS avg_rating REAL DEFAULT 0;
ALTER TABLE marketplace_seller_scores ADD COLUMN IF NOT EXISTS avg_response_time_mins REAL DEFAULT 0;

-- medical_providers: 4 column(s) the development database is missing
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS provider_name TEXT DEFAULT '';
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS license_no TEXT;
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS zone TEXT;
ALTER TABLE medical_providers ADD COLUMN IF NOT EXISTS is_verified INTEGER DEFAULT 0;

-- move_passes: 4 column(s) the development database is missing
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE move_passes ADD COLUMN IF NOT EXISTS moving_date TEXT;

-- platform_settings: 1 column(s) the development database is missing
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- shop_categories: 5 column(s) the development database is missing
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS business_model TEXT DEFAULT '';
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS commission_percent REAL DEFAULT 5.0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS convenience_fee REAL DEFAULT 0.0;
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS registration_fields TEXT DEFAULT '[]';
ALTER TABLE shop_categories ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- shop_orders: 3 column(s) the development database is missing
ALTER TABLE shop_orders ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE shop_orders ADD COLUMN IF NOT EXISTS items TEXT DEFAULT '';
ALTER TABLE shop_orders ADD COLUMN IF NOT EXISTS payment_method TEXT;

-- shop_products: 1 column(s) the development database is missing
ALTER TABLE shop_products ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- shop_qa: 2 column(s) the development database is missing
ALTER TABLE shop_qa ADD COLUMN IF NOT EXISTS answered_by TEXT;
ALTER TABLE shop_qa ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_advance_account: 1 column(s) the development database is missing
ALTER TABLE society_advance_account ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

-- society_agm_minutes: 1 column(s) the development database is missing
ALTER TABLE society_agm_minutes ADD COLUMN IF NOT EXISTS published_by TEXT;

-- society_amenities: 7 column(s) the development database is missing
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS capacity INTEGER;
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS hourly_rate REAL DEFAULT 0;
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS booking_advance_days INTEGER DEFAULT 7;
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS available_from TEXT DEFAULT '06:00';
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS available_until TEXT DEFAULT '22:00';
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
ALTER TABLE society_amenities ADD COLUMN IF NOT EXISTS rules TEXT;

-- society_amenity_locks: 1 column(s) the development database is missing
ALTER TABLE society_amenity_locks ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';

-- society_asset_maintenance_log: 3 column(s) the development database is missing
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS service_type TEXT;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS service_date TIMESTAMPTZ;
ALTER TABLE society_asset_maintenance_log ADD COLUMN IF NOT EXISTS notes TEXT;

-- society_assets: 3 column(s) the development database is missing
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE society_assets ADD COLUMN IF NOT EXISTS amc_expiry TIMESTAMPTZ;

-- society_billing_config: 2 column(s) the development database is missing
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS sinking_fund_rate_percent REAL;
ALTER TABLE society_billing_config ADD COLUMN IF NOT EXISTS late_penalty_rate_percent REAL DEFAULT 21;

-- society_budget: 2 column(s) the development database is missing
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS year TEXT DEFAULT '';
ALTER TABLE society_budget ADD COLUMN IF NOT EXISTS total_amount REAL;

-- society_budget_items: 2 column(s) the development database is missing
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS allocated_amount REAL;
ALTER TABLE society_budget_items ADD COLUMN IF NOT EXISTS spent_amount REAL DEFAULT 0;

-- society_charge_heads: 1 column(s) the development database is missing
ALTER TABLE society_charge_heads ADD COLUMN IF NOT EXISTS gst_applicable INTEGER DEFAULT 0;

-- society_complaint_activity: 3 column(s) the development database is missing
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS old_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS new_status TEXT;
ALTER TABLE society_complaint_activity ADD COLUMN IF NOT EXISTS changed_by TEXT;

-- society_delivery_preferences: 3 column(s) the development database is missing
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS leave_at_gate INTEGER DEFAULT 0;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS preferred_window TEXT;
ALTER TABLE society_delivery_preferences ADD COLUMN IF NOT EXISTS package_location TEXT;

-- society_document_templates: 2 column(s) the development database is missing
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';
ALTER TABLE society_document_templates ADD COLUMN IF NOT EXISTS content TEXT DEFAULT '';

-- society_emergency_alerts: 3 column(s) the development database is missing
ALTER TABLE society_emergency_alerts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE society_emergency_alerts ADD COLUMN IF NOT EXISTS flat_number TEXT;
ALTER TABLE society_emergency_alerts ADD COLUMN IF NOT EXISTS resolved_at TEXT;

-- society_fire_safety: 2 column(s) the development database is missing
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS last_inspection TIMESTAMPTZ;
ALTER TABLE society_fire_safety ADD COLUMN IF NOT EXISTS next_due TIMESTAMPTZ;

-- society_flat_ledger: 2 column(s) the development database is missing
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS carpet_area REAL;
ALTER TABLE society_flat_ledger ADD COLUMN IF NOT EXISTS outstanding_balance REAL DEFAULT 0;

-- society_forum_replies: 1 column(s) the development database is missing
ALTER TABLE society_forum_replies ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;

-- society_forum_topics: 1 column(s) the development database is missing
ALTER TABLE society_forum_topics ADD COLUMN IF NOT EXISTS author_id TEXT DEFAULT '';

-- society_gates: 1 column(s) the development database is missing
ALTER TABLE society_gates ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';

-- society_guard_shift_swaps: 3 column(s) the development database is missing
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS shift_id TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS requested_by TEXT DEFAULT '';
ALTER TABLE society_guard_shift_swaps ADD COLUMN IF NOT EXISTS requested_with TEXT;

-- society_guard_shifts: 1 column(s) the development database is missing
ALTER TABLE society_guard_shifts ADD COLUMN IF NOT EXISTS shift_name TEXT;

-- society_intercom_sessions: 3 column(s) the development database is missing
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS caller_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS receiver_id TEXT;
ALTER TABLE society_intercom_sessions ADD COLUMN IF NOT EXISTS duration INTEGER DEFAULT 0;

-- society_ivr_logs: 1 column(s) the development database is missing
ALTER TABLE society_ivr_logs ADD COLUMN IF NOT EXISTS phone_called TEXT DEFAULT '';

-- society_members: 3 column(s) the development database is missing
ALTER TABLE society_members ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'resident';
ALTER TABLE society_members ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;
ALTER TABLE society_members ADD COLUMN IF NOT EXISTS added_by TEXT;

-- society_messages: 1 column(s) the development database is missing
ALTER TABLE society_messages ADD COLUMN IF NOT EXISTS content TEXT DEFAULT '';

-- society_notices: 2 column(s) the development database is missing
ALTER TABLE society_notices ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'normal';
ALTER TABLE society_notices ADD COLUMN IF NOT EXISTS is_active INTEGER DEFAULT 1;

-- society_patrol_logs: 4 column(s) the development database is missing
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS scanned_checkpoints_json TEXT;
ALTER TABLE society_patrol_logs ADD COLUMN IF NOT EXISTS completion_percent REAL;

-- society_patrol_routes: 2 column(s) the development database is missing
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';
ALTER TABLE society_patrol_routes ADD COLUMN IF NOT EXISTS checkpoints_json TEXT DEFAULT '';

-- society_payment_receipts: 3 column(s) the development database is missing
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS amount_paid REAL DEFAULT 0;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS payment_mode TEXT;
ALTER TABLE society_payment_receipts ADD COLUMN IF NOT EXISTS transaction_ref TEXT;

-- society_penalty_ledger: 2 column(s) the development database is missing
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS amount REAL DEFAULT 0;
ALTER TABLE society_penalty_ledger ADD COLUMN IF NOT EXISTS reverse_reason TEXT;

-- society_police_verification: 2 column(s) the development database is missing
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS member_id TEXT DEFAULT '';
ALTER TABLE society_police_verification ADD COLUMN IF NOT EXISTS document_url TEXT DEFAULT '';

-- society_polls: 7 column(s) the development database is missing
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS title TEXT DEFAULT '';
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS poll_type TEXT DEFAULT 'single';
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS is_anonymous INTEGER DEFAULT 0;
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS starts_at TEXT;
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS ends_at TEXT;
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- society_settings: 9 column(s) the development database is missing
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS auto_approve_expected INTEGER DEFAULT 0;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS visitor_photo_required INTEGER DEFAULT 1;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS id_card_required INTEGER DEFAULT 1;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS max_visitors_per_flat INTEGER DEFAULT 10;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS guard_shift_start TEXT DEFAULT '06:00';
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS guard_shift_end TEXT DEFAULT '22:00';
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS maintenance_due_day INTEGER DEFAULT 5;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS late_fee_percentage REAL DEFAULT 5.0;
ALTER TABLE society_settings ADD COLUMN IF NOT EXISTS updated_at TEXT DEFAULT CURRENT_TIMESTAMP;

-- society_staff_attendance: 3 column(s) the development database is missing
ALTER TABLE society_staff_attendance ADD COLUMN IF NOT EXISTS marked_by TEXT;
ALTER TABLE society_staff_attendance ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'present';
ALTER TABLE society_staff_attendance ADD COLUMN IF NOT EXISTS notes TEXT;

-- society_staff_payroll: 2 column(s) the development database is missing
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS net_salary REAL;
ALTER TABLE society_staff_payroll ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';

-- society_staff_ratings: 1 column(s) the development database is missing
ALTER TABLE society_staff_ratings ADD COLUMN IF NOT EXISTS member_id TEXT DEFAULT '';

-- society_tally_exports: 1 column(s) the development database is missing
ALTER TABLE society_tally_exports ADD COLUMN IF NOT EXISTS xml_payload TEXT;

-- society_utility_deliveries: 2 column(s) the development database is missing
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS gate_id TEXT;
ALTER TABLE society_utility_deliveries ADD COLUMN IF NOT EXISTS utility_type TEXT;

-- society_vehicle_log: 4 column(s) the development database is missing
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS entry_time TIMESTAMPTZ;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS exit_time TIMESTAMPTZ;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS vehicle_photo_url TEXT;
ALTER TABLE society_vehicle_log ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'entered';

-- society_vendor_invoices: 2 column(s) the development database is missing
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE society_vendor_invoices ADD COLUMN IF NOT EXISTS payment_ref TEXT;

-- society_vendors: 1 column(s) the development database is missing
ALTER TABLE society_vendors ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';

-- society_visitor_blacklist: 3 column(s) the development database is missing
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS name TEXT DEFAULT '';
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE society_visitor_blacklist ADD COLUMN IF NOT EXISTS added_by TEXT;

-- society_visitor_preapprovals: 1 column(s) the development database is missing
ALTER TABLE society_visitor_preapprovals ADD COLUMN IF NOT EXISTS is_revoked INTEGER DEFAULT 0;

-- users: 5 column(s) the development database is missing
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_method TEXT DEFAULT 'phone_otp';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_count INTEGER DEFAULT 0;

-- vehicles: 7 column(s) the development database is missing
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS society_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS user_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS flat_number TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS license_plate TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS make_model TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS parking_slot TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS rfid_tag_id TEXT;

-- equipment_listings: absent from a fresh migration; review the PostgreSQL DDL by hand
--   (the SQLite definition is in 076_fresh_migration_parity.sqlite.sql).

-- loyalty_wallets: absent from a fresh migration; review the PostgreSQL DDL by hand
--   (the SQLite definition is in 076_fresh_migration_parity.sqlite.sql).

-- volunteer_tasks: absent from a fresh migration; review the PostgreSQL DDL by hand
--   (the SQLite definition is in 076_fresh_migration_parity.sqlite.sql).
