-- Migration 079: columns declared by migrations that never executed
--
-- When two migrations declare the same table with CREATE TABLE IF NOT EXISTS,
-- the earlier one wins and the later, richer definition silently does nothing.
-- Unlike the drift repaired in 076, this affects every database equally, so
-- there was no working copy to compare against and nothing looked wrong.
--
-- medical_doctors is the clearest case: 024 creates it with 11 columns and 026
-- declares 17. 026's definition has never executed, so its own
-- CREATE INDEX ... (geohash) failed on every migration run -- the only visible
-- symptom of a table missing nine columns the application queries.
--
-- Generated by scripts/generate-declared-parity-migration.js, by unioning every
-- CREATE TABLE in the migration set and diffing against the live schema. The
-- union is additive: a table that was deliberately reshaped keeps both sets of
-- columns rather than losing either.

-- carpool_rides: 6 column(s) declared by a migration that never ran
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS origin TEXT;
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS destination TEXT;
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS estimated_arrival TEXT;
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS seats_available TEXT;
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS car_model TEXT;
ALTER TABLE carpool_rides ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- delivery_agents: 5 column(s) declared by a migration that never ran
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS region_id TEXT;
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS current_lat REAL;
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS current_lng REAL;
ALTER TABLE delivery_agents ADD COLUMN IF NOT EXISTS rating REAL;

-- event_tickets: 3 column(s) declared by a migration that never ran
ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS ticket_ref TEXT;
ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS quantity INTEGER;
ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS total_amount REAL;

-- feature_flags: 1 column(s) declared by a migration that never ran
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS id TEXT;

-- file_uploads: 7 column(s) declared by a migration that never ran
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS module TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS mime_type TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS thumbnail_path TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS is_public TEXT;
ALTER TABLE file_uploads ADD COLUMN IF NOT EXISTS uploaded_at TEXT;

-- home_service_categories: 1 column(s) declared by a migration that never ran
ALTER TABLE home_service_categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

-- home_service_providers: 1 column(s) declared by a migration that never ran
ALTER TABLE home_service_providers ADD COLUMN IF NOT EXISTS geohash TEXT;

-- job_alerts: 3 column(s) declared by a migration that never ran
ALTER TABLE job_alerts ADD COLUMN IF NOT EXISTS remote_only TEXT;
ALTER TABLE job_alerts ADD COLUMN IF NOT EXISTS frequency TEXT;
ALTER TABLE job_alerts ADD COLUMN IF NOT EXISTS last_sent TEXT;

-- job_applications: 5 column(s) declared by a migration that never ran
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS applicant_name TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS applicant_phone TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS experience_summary TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS applied_at TIMESTAMP;

-- marketplace_listings: 1 column(s) declared by a migration that never ran
ALTER TABLE marketplace_listings ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- medical_appointments: 1 column(s) declared by a migration that never ran
ALTER TABLE medical_appointments ADD COLUMN IF NOT EXISTS payment_status TEXT;

-- medical_doctors: 9 column(s) declared by a migration that never ran
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS qualification TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS license_no TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS clinic_name TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS latitude REAL;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS longitude REAL;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS geohash TEXT;
ALTER TABLE medical_doctors ADD COLUMN IF NOT EXISTS is_verified BOOLEAN;

-- order_items: 1 column(s) declared by a migration that never ran
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_at_buy TEXT;

-- orders: 2 column(s) declared by a migration that never ran
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id TEXT;

-- referrals: 4 column(s) declared by a migration that never ran
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS referee_id TEXT;
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS referral_code TEXT;
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS reward_issued INTEGER;
ALTER TABLE referrals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- shop_reviews: 5 column(s) declared by a migration that never ran
ALTER TABLE shop_reviews ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE shop_reviews ADD COLUMN IF NOT EXISTS comment TEXT;
ALTER TABLE shop_reviews ADD COLUMN IF NOT EXISTS reply TEXT;
ALTER TABLE shop_reviews ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE shop_reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- shop_staff: 7 column(s) declared by a migration that never ran
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS shift TEXT;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS commission REAL;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS joined_date TIMESTAMP;
ALTER TABLE shop_staff ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- societies: 2 column(s) declared by a migration that never ran
ALTER TABLE societies ADD COLUMN IF NOT EXISTS subscription_fee REAL;
ALTER TABLE societies ADD COLUMN IF NOT EXISTS is_active BOOLEAN;

-- society_complaints: 5 column(s) declared by a migration that never ran
ALTER TABLE society_complaints ADD COLUMN IF NOT EXISTS filed_by TEXT;
ALTER TABLE society_complaints ADD COLUMN IF NOT EXISTS flat_number TEXT;
ALTER TABLE society_complaints ADD COLUMN IF NOT EXISTS assigned_to TEXT;
ALTER TABLE society_complaints ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE society_complaints ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- society_members: 1 column(s) declared by a migration that never ran
ALTER TABLE society_members ADD COLUMN IF NOT EXISTS status TEXT;

-- society_notices: 1 column(s) declared by a migration that never ran
ALTER TABLE society_notices ADD COLUMN IF NOT EXISTS created_by TEXT;

-- society_polls: 1 column(s) declared by a migration that never ran
ALTER TABLE society_polls ADD COLUMN IF NOT EXISTS expires_at TEXT;
