-- Migration 079: columns declared by migrations that never executed
--
-- When two migrations declare the same table with CREATE TABLE IF NOT EXISTS,
-- the earlier one wins and the later, richer definition silently does nothing.
-- Unlike the drift repaired in 076, this affects every database equally, so
-- there was no working copy to compare against and nothing looked wrong.
--
-- medical_doctors is the clearest case: 024 creates it with 11 columns and 026
-- declares 17. 026's definition has never executed, so its own
-- CREATE INDEX ... (geohash) failed on every migration run -- the only visible
-- symptom of a table missing nine columns the application queries.
--
-- Generated by scripts/generate-declared-parity-migration.js, by unioning every
-- CREATE TABLE in the migration set and diffing against the live schema. The
-- union is additive: a table that was deliberately reshaped keeps both sets of
-- columns rather than losing either.

-- carpool_rides: 6 column(s) declared by a migration that never ran
ALTER TABLE carpool_rides ADD COLUMN origin TEXT;
ALTER TABLE carpool_rides ADD COLUMN destination TEXT;
ALTER TABLE carpool_rides ADD COLUMN estimated_arrival TEXT;
ALTER TABLE carpool_rides ADD COLUMN seats_available INTEGER;
ALTER TABLE carpool_rides ADD COLUMN car_model TEXT;
ALTER TABLE carpool_rides ADD COLUMN updated_at DATETIME;

-- delivery_agents: 5 column(s) declared by a migration that never ran
ALTER TABLE delivery_agents ADD COLUMN region_id TEXT;
ALTER TABLE delivery_agents ADD COLUMN status TEXT;
ALTER TABLE delivery_agents ADD COLUMN current_lat REAL;
ALTER TABLE delivery_agents ADD COLUMN current_lng REAL;
ALTER TABLE delivery_agents ADD COLUMN rating REAL;

-- event_tickets: 3 column(s) declared by a migration that never ran
ALTER TABLE event_tickets ADD COLUMN ticket_ref TEXT;
ALTER TABLE event_tickets ADD COLUMN quantity INTEGER;
ALTER TABLE event_tickets ADD COLUMN total_amount REAL;

-- feature_flags: 1 column(s) declared by a migration that never ran
ALTER TABLE feature_flags ADD COLUMN id TEXT;

-- file_uploads: 7 column(s) declared by a migration that never ran
ALTER TABLE file_uploads ADD COLUMN user_id TEXT;
ALTER TABLE file_uploads ADD COLUMN module TEXT;
ALTER TABLE file_uploads ADD COLUMN entity_id TEXT;
ALTER TABLE file_uploads ADD COLUMN mime_type TEXT;
ALTER TABLE file_uploads ADD COLUMN thumbnail_path TEXT;
ALTER TABLE file_uploads ADD COLUMN is_public INTEGER;
ALTER TABLE file_uploads ADD COLUMN uploaded_at DATETIME;

-- home_service_categories: 1 column(s) declared by a migration that never ran
ALTER TABLE home_service_categories ADD COLUMN created_at DATETIME;

-- home_service_providers: 1 column(s) declared by a migration that never ran
ALTER TABLE home_service_providers ADD COLUMN geohash TEXT;

-- job_alerts: 3 column(s) declared by a migration that never ran
ALTER TABLE job_alerts ADD COLUMN remote_only INTEGER;
ALTER TABLE job_alerts ADD COLUMN frequency TEXT;
ALTER TABLE job_alerts ADD COLUMN last_sent DATETIME;

-- job_applications: 5 column(s) declared by a migration that never ran
ALTER TABLE job_applications ADD COLUMN user_id TEXT;
ALTER TABLE job_applications ADD COLUMN applicant_name TEXT;
ALTER TABLE job_applications ADD COLUMN applicant_phone TEXT;
ALTER TABLE job_applications ADD COLUMN experience_summary TEXT;
ALTER TABLE job_applications ADD COLUMN applied_at DATETIME;

-- marketplace_listings: 1 column(s) declared by a migration that never ran
ALTER TABLE marketplace_listings ADD COLUMN updated_at DATETIME;

-- medical_appointments: 1 column(s) declared by a migration that never ran
ALTER TABLE medical_appointments ADD COLUMN payment_status TEXT;

-- medical_doctors: 9 column(s) declared by a migration that never ran
ALTER TABLE medical_doctors ADD COLUMN user_id TEXT;
ALTER TABLE medical_doctors ADD COLUMN qualification TEXT;
ALTER TABLE medical_doctors ADD COLUMN license_no TEXT;
ALTER TABLE medical_doctors ADD COLUMN clinic_name TEXT;
ALTER TABLE medical_doctors ADD COLUMN address TEXT;
ALTER TABLE medical_doctors ADD COLUMN latitude REAL;
ALTER TABLE medical_doctors ADD COLUMN longitude REAL;
ALTER TABLE medical_doctors ADD COLUMN geohash TEXT;
ALTER TABLE medical_doctors ADD COLUMN is_verified INTEGER;

-- order_items: 1 column(s) declared by a migration that never ran
ALTER TABLE order_items ADD COLUMN price_at_buy REAL;

-- orders: 2 column(s) declared by a migration that never ran
ALTER TABLE orders ADD COLUMN status TEXT;
ALTER TABLE orders ADD COLUMN payment_id TEXT;

-- referrals: 4 column(s) declared by a migration that never ran
ALTER TABLE referrals ADD COLUMN referee_id TEXT;
ALTER TABLE referrals ADD COLUMN referral_code TEXT;
ALTER TABLE referrals ADD COLUMN reward_issued INTEGER;
ALTER TABLE referrals ADD COLUMN updated_at DATETIME;

-- shop_reviews: 5 column(s) declared by a migration that never ran
ALTER TABLE shop_reviews ADD COLUMN customer_name TEXT;
ALTER TABLE shop_reviews ADD COLUMN comment TEXT;
ALTER TABLE shop_reviews ADD COLUMN reply TEXT;
ALTER TABLE shop_reviews ADD COLUMN status TEXT;
ALTER TABLE shop_reviews ADD COLUMN updated_at DATETIME;

-- shop_staff: 7 column(s) declared by a migration that never ran
ALTER TABLE shop_staff ADD COLUMN phone TEXT;
ALTER TABLE shop_staff ADD COLUMN email TEXT;
ALTER TABLE shop_staff ADD COLUMN status TEXT;
ALTER TABLE shop_staff ADD COLUMN shift TEXT;
ALTER TABLE shop_staff ADD COLUMN commission REAL;
ALTER TABLE shop_staff ADD COLUMN joined_date DATETIME;
ALTER TABLE shop_staff ADD COLUMN updated_at DATETIME;

-- societies: 2 column(s) declared by a migration that never ran
ALTER TABLE societies ADD COLUMN subscription_fee REAL;
ALTER TABLE societies ADD COLUMN is_active INTEGER;

-- society_complaints: 5 column(s) declared by a migration that never ran
ALTER TABLE society_complaints ADD COLUMN filed_by TEXT;
ALTER TABLE society_complaints ADD COLUMN flat_number TEXT;
ALTER TABLE society_complaints ADD COLUMN assigned_to TEXT;
ALTER TABLE society_complaints ADD COLUMN admin_notes TEXT;
ALTER TABLE society_complaints ADD COLUMN updated_at TEXT;

-- society_members: 1 column(s) declared by a migration that never ran
ALTER TABLE society_members ADD COLUMN status TEXT;

-- society_notices: 1 column(s) declared by a migration that never ran
ALTER TABLE society_notices ADD COLUMN created_by TEXT;

-- society_polls: 1 column(s) declared by a migration that never ran
ALTER TABLE society_polls ADD COLUMN expires_at TEXT;
