-- Migration 082: tables that were only ever created at runtime
--
-- Each table below is created by a controller on first use, inside a catch block
-- that tests for "no such table". That works in development, where the
-- application owns the database, and is unsafe in production: the application
-- role usually has no DDL rights, two concurrent first-requests race, and until
-- somebody calls the endpoint the table does not exist at all.
--
-- medical_requests is the clearest case. Nothing declares it, so logging an
-- emergency medical request only works because an earlier request already failed
-- and created the table on its way out.
--
-- The definitions are lifted from the CREATE TABLE statements in the source, not
-- rewritten, so the migrated shape is the one the code already expects. The
-- runtime fallbacks can stay where they are -- they simply stop being reachable.
--
-- Generated by scripts/generate-runtime-table-migration.js.


-- admin_ads (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_ads (
        id TEXT PRIMARY KEY,
        image_url TEXT NOT NULL,
        deep_link TEXT,
        status TEXT DEFAULT 'active',
        clicks INTEGER DEFAULT 0,
        impressions INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_alerts_log (from src\modules\crm\controllers\admin-alerts.controller.js)
CREATE TABLE IF NOT EXISTS admin_alerts_log (
      id VARCHAR(255) PRIMARY KEY,
      alert_type VARCHAR(50),
      target_audience VARCHAR(50),
      message TEXT,
      admin_id VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- admin_animal_requests (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_animal_requests (
        id TEXT PRIMARY KEY,
        reporter_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        animal_type TEXT NOT NULL,
        severity TEXT NOT NULL,
        location TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        dispatched INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_animal_rescue (from src\modules\crm\controllers\admin-animal.controller.js)
CREATE TABLE IF NOT EXISTS admin_animal_rescue (
      id VARCHAR(255) PRIMARY KEY,
      reporter_name VARCHAR(255),
      phone VARCHAR(50),
      animal_type VARCHAR(100),
      severity VARCHAR(50),
      location TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      dispatched BOOLEAN DEFAULT false,
      admin_id VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- admin_backups (from src\modules\crm\controllers\admin-backups.controller.js)
CREATE TABLE IF NOT EXISTS admin_backups (
            id VARCHAR(255) PRIMARY KEY,
            filename VARCHAR(255),
            provider VARCHAR(100),
            size_mb DECIMAL(10,2),
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- admin_charity_campaigns (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_charity_campaigns (
        id TEXT PRIMARY KEY,
        ngo_name TEXT NOT NULL,
        title TEXT NOT NULL,
        goal_amount REAL DEFAULT 0,
        raised_amount REAL DEFAULT 0,
        status TEXT DEFAULT 'active',
        verified_ngo INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_civic_issues (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_civic_issues (
        id TEXT PRIMARY KEY,
        reporter_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        category TEXT NOT NULL,
        issue_type TEXT NOT NULL,
        description TEXT NOT NULL,
        department TEXT,
        status TEXT DEFAULT 'pending',
        escalated INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_krishi_listings (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_krishi_listings (
        id TEXT PRIMARY KEY,
        seller_id TEXT,
        title TEXT NOT NULL,
        description TEXT,
        price TEXT,
        type TEXT DEFAULT 'crop',
        verified_farmer INTEGER DEFAULT 0,
        auto_expire INTEGER DEFAULT 1,
        status TEXT DEFAULT 'active',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_localization (from src\modules\crm\controllers\admin-languages.controller.js)
CREATE TABLE IF NOT EXISTS admin_localization (
            id VARCHAR(50) PRIMARY KEY,
            active_languages TEXT,
            dictionary_overrides TEXT,
            updated_by VARCHAR(255),
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- admin_medical_requests (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_medical_requests (
        id TEXT PRIMARY KEY,
        patient_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        request_type TEXT NOT NULL,
        blood_group TEXT,
        urgency TEXT NOT NULL,
        location TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        dispatched INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_mobility_fleet (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_mobility_fleet (
        id TEXT PRIMARY KEY,
        driver_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        vehicle_type TEXT DEFAULT 'auto',
        rc_number TEXT,
        verified_driver INTEGER DEFAULT 0,
        status TEXT DEFAULT 'active',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_scrap_requests (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_scrap_requests (
        id TEXT PRIMARY KEY,
        user_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        scrap_type TEXT NOT NULL,
        estimated_weight TEXT,
        address TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        dispatched INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_settings (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
);

-- admin_support_tickets (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_support_tickets (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        domain TEXT DEFAULT 'general',
        subject TEXT NOT NULL,
        description TEXT NOT NULL,
        status TEXT DEFAULT 'open',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- admin_utility_bills (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS admin_utility_bills (
        id TEXT PRIMARY KEY,
        customer_name TEXT NOT NULL,
        phone TEXT NOT NULL,
        provider_type TEXT NOT NULL,
        consumer_number TEXT NOT NULL,
        amount REAL NOT NULL,
        status TEXT DEFAULT 'pending',
        payment_cleared INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- charity_campaigns (from src\modules\crm\controllers\admin-charity.controller.js)
CREATE TABLE IF NOT EXISTS charity_campaigns (
            id VARCHAR(255) PRIMARY KEY,
            ngo_name VARCHAR(255),
            title VARCHAR(255),
            goal_amount DECIMAL(12,2) DEFAULT 0,
            raised_amount DECIMAL(12,2) DEFAULT 0,
            status VARCHAR(50) DEFAULT 'active',
            verified_ngo BOOLEAN DEFAULT false,
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- civic_issues (from src\modules\crm\controllers\admin-civic.controller.js)
CREATE TABLE IF NOT EXISTS civic_issues (
            id VARCHAR(255) PRIMARY KEY,
            reporter_name VARCHAR(255),
            phone VARCHAR(50),
            category VARCHAR(50),
            issue_type VARCHAR(100),
            department VARCHAR(100),
            description TEXT,
            status VARCHAR(50) DEFAULT 'pending',
            escalated BOOLEAN DEFAULT false,
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- environment_scrap (from src\modules\crm\controllers\admin-environment.controller.js)
CREATE TABLE IF NOT EXISTS environment_scrap (
            id VARCHAR(255) PRIMARY KEY,
            user_name VARCHAR(255),
            phone VARCHAR(50),
            scrap_type VARCHAR(255),
            estimated_weight VARCHAR(100),
            address TEXT,
            status VARCHAR(50) DEFAULT 'pending',
            dispatched BOOLEAN DEFAULT false,
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- franchise_lead_crm (from src\scripts\qa_audit.js)
CREATE TABLE IF NOT EXISTS franchise_lead_crm (
        id TEXT PRIMARY KEY,
        business_name TEXT NOT NULL,
        category TEXT,
        phone TEXT,
        pincode TEXT,
        status TEXT DEFAULT 'SCRAPED',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- logistics_agents (from src\modules\logistics\controllers\agents.controller.js)
CREATE TABLE IF NOT EXISTS logistics_agents (
              id SERIAL PRIMARY KEY,
              name VARCHAR(255),
              status VARCHAR(50),
              current_order VARCHAR(100),
              battery VARCHAR(20),
              location VARCHAR(100)
);

-- loyalty_points (from src\modules\crm\routes\admin.routes.js)
CREATE TABLE IF NOT EXISTS loyalty_points (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        points INTEGER,
        reason TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- medical_requests (from src\modules\crm\controllers\admin-medical.controller.js)
CREATE TABLE IF NOT EXISTS medical_requests (
            id VARCHAR(255) PRIMARY KEY,
            patient_name VARCHAR(255),
            phone VARCHAR(50),
            request_type VARCHAR(100),
            blood_group VARCHAR(10),
            urgency VARCHAR(50),
            location TEXT,
            status VARCHAR(50) DEFAULT 'pending',
            dispatched BOOLEAN DEFAULT false,
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- messages (from src\create_messages_table.js)
CREATE TABLE IF NOT EXISTS messages (
        id TEXT PRIMARY KEY,
        sender_id TEXT REFERENCES users(id) ON DELETE CASCADE,
        receiver_id TEXT REFERENCES users(id) ON DELETE CASCADE,
        message_text TEXT,
        is_read BOOLEAN DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- user_fcm_tokens (from src\modules\core\routes\notification.routes.js)
CREATE TABLE IF NOT EXISTS user_fcm_tokens (
          id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL,
          fcm_token TEXT NOT NULL,
          platform TEXT DEFAULT 'android',
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          UNIQUE(user_id, fcm_token)
);

-- utility_bills (from src\modules\crm\controllers\admin-bills.controller.js)
CREATE TABLE IF NOT EXISTS utility_bills (
            id VARCHAR(255) PRIMARY KEY,
            customer_name VARCHAR(255),
            phone VARCHAR(50),
            provider_type VARCHAR(100),
            consumer_number VARCHAR(100),
            amount DECIMAL(10,2),
            status VARCHAR(50) DEFAULT 'pending',
            payment_cleared BOOLEAN DEFAULT false,
            created_by VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
